project_id = "ewquysvcjuqdkfieeuxd"

[functions.admin-action]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-cleanup-orphans]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true
