// Bộ câu thử ĐỘC LẬP cho ranh giới Tarot – y khoa (lib/lomiTarotGate).
//
// Mỗi đợt (R2…R6) do một tác nhân khác viết mà KHÔNG đọc source, rồi chạy qua bộ lọc đang có TRƯỚC khi sửa. Kết quả lần chạy đầu
// (số câu y khoa bị chặn / tổng) được ghi ở HOLDOUT để biết bộ lọc khái quát tới đâu với câu chưa từng thấy:
// sau khi sửa, cả bộ được giữ lại ở đây làm test hồi quy — nên con số "đạt hết" của file này KHÔNG phải độ phủ ngoài thực tế.
export const HOLDOUT = { R1: "128/261 (bộ lọc đầu tiên của đợt này)", R2: "146/160", R3: "122/150", R4: "142/150", R5: "107/150 (cố ý chỉ dùng lời tả thường, không có chữ y khoa)", R6: "136/160 (trộn 60% câu thường / 40% câu khó)" };

export const BLIND_MEDICAL: string[] = [
  "Mẹ tôi bị ung thư vú giai đoạn 2, liệu mẹ có chữa khỏi được không?",
  "Tôi có bị tiểu đường không?",
  "Ba em bị đột quỵ tuần trước, xem giúp em ba có hồi phục được không",
  "Nội tui có qua nổi đợt viêm phổi này hông?",
  "Bà ngoại bị tai biến nằm một chỗ, bao giờ bà đi lại được?",
  "Chồng chị đang chạy thận, ảnh còn sống được mấy năm nữa?",
  "Lá bài nói gì về ca mổ dạ dày thứ Năm này của tôi?",
  "Xem giúp em kết quả sinh thiết hạch tuần sau",
  "Bốc cho anh một lá coi bệnh gan của anh sao rồi",
  "Bé nhà em 3 tuổi chưa nói, bé có bị tự kỷ không?",
  "Khối u ở cổ của mình lành hay ác?",
  "Hoá trị đợt 3 của mẹ có đáp ứng không?",
  "Ghép thận cho bố có thành công không?",
  "Uống thuốc nam có hết xơ gan không?",
  "Em có nên chuyển viện cho ba lên tuyến trên không?",
  "Bao giờ con trai tôi được ra viện?",
  "Ung thư của dì có di căn không?",
  "U tuyến giáp của chị mổ rồi có tái phát không?",
  "Thai của em có giữ được không?",
  "Tôi có nên ngừng uống thuốc huyết áp không?",
  "Vợ tôi làm IVF lần này có đậu không?",
  "Vợ chồng em hiếm muộn 5 năm rồi, năm nay có con được chưa?",
  "Mình có bị trầm cảm không Tarot ơi?",
  "Tớ hay hồi hộp khó thở, có phải tớ bị rối loạn lo âu không?",
  "Bệnh lao phổi của chú tôi điều trị bao lâu thì khỏi?",
  "Cơn hen của bé có hết khi lớn lên không?",
  "Bạn thân em có nhiễm HIV thật không?",
  "Viêm gan B của người yêu em có chuyển sang ung thư gan không?",
  "Sếp tôi nhập viện vì nhồi máu cơ tim, sếp có qua khỏi không?",
  "Bệnh lupus của cô giáo em có sống được lâu không?",
  "Tui bị thoát vị đĩa đệm, nên mổ hay tập vật lý trị liệu?",
  "Mổ mắt cận lần này có an toàn không, bốc bài giúp mình",
  "Bà nội bị Alzheimer có nhớ lại con cháu được không?",
  "Bệnh Parkinson của ba có nặng thêm không?",
  "Bệnh động kinh của con em lớn lên có hết hông chị?",
  "Em bị sốt xuất huyết ngày thứ 4, có trở nặng không?",
  "Kết quả xét nghiệm máu ngày mai của tôi có bình thường không?",
  "Chụp MRI não ra kết quả xấu hay tốt?",
  "Em bầu 12 tuần, em bé có khoẻ mạnh không?",
  "Lần mang thai này em có bị sảy nữa không?",
  "Tôi nên sinh mổ hay sinh thường thì an toàn hơn?",
  "Bé sinh non 30 tuần nhà chị có nuôi được không?",
  "Anh có bị vô sinh không?",
  "Vết bỏng của con bao lâu thì lành?",
  "Chân gãy của anh bao giờ liền xương?",
  "Bệnh vảy nến của em có chữa dứt được không?",
  "Zona thần kinh của mẹ bao giờ hết đau?",
  "Bệnh gout của ba có nặng lên không?",
  "Cường giáp của em nên uống thuốc hay uống iod phóng xạ?",
  "U xơ tử cung của chị có cần mổ không?",
  "Polyp đại tràng của tôi có hoá ung thư không?",
  "Suy thận độ 3 của bố tôi có phải chạy thận không?",
  "Ngoại nằm ICU ba ngày rồi, ngoại có tỉnh lại không?",
  "Mẹ chồng em còn được bao lâu nữa?",
  "Bài Tarot cho biết tôi đang mắc bệnh gì?",
  "Tôi dương tính COVID, có bị biến chứng phổi không?",
  "Em trai tôi có bị tâm thần phân liệt không?",
  "Thay khớp gối cho mẹ có ổn không?",
  "Nên cho ba xạ trị hay chỉ chăm sóc giảm nhẹ?",
  "Đổi bác sĩ điều trị thì bệnh của em có đỡ hơn không?",
  "U nang buồng trứng của em có tự tiêu không?",
  "Bị basedow thì chị có mang thai được không?",
  "Tim thai yếu, em bé có qua được không?",
  "Bệnh giang mai của em chữa có khỏi hẳn không?",
  "Trải bài xem sức khoẻ ba tôi có qua nổi năm nay không",
  "Huyết áp của mẹ lên xuống thất thường, mẹ có bị tai biến không?",
  "Thuốc trầm cảm bác sĩ kê, em có nên bỏ không?",
  "Vợ anh bị thai lưu hai lần, lần này có sinh được không?",
  "Con gái tôi chậm nói, lá bài bảo con có bị gì không?",
  "Mình mất ngủ triền miên, có phải bị bệnh gì nặng không?",
  "Nốt ruồi này có phải ung thư da không?",
  "Dì út mổ tim hở ngày mai, ca mổ có suôn sẻ không?",
  "me e co khoi benh khong",
  "ba toi con song duoc bao lau nua",
  "toi co bi ung thu khong",
  "xem giup em benh tieu duong cua me co nang them khong",
  "ong ngoai bi tai bien co qua khoi khong",
  "chong em bi xo gan co chua duoc khong",
  "em co thai duoc khong",
  "lam ivf lan 2 co thanh cong khong",
  "ket qua sinh thiet cua toi la lanh tinh hay ac tinh",
  "bac si bao phai mo gap, toi co nen mo khong",
  "be nha chi bi sot xuat huyet co sao khong",
  "bo toi bi dot quy co tinh lai khong",
  "anh co nen bo thuoc tay chuyen sang thuoc nam khong",
  "vo toi bi tram cam sau sinh bao gio het",
  "toi co bi roi loan lo au khong",
  "con toi co bi tu ky khong",
  "ba noi bi suy than giai doan cuoi con duoc may thang",
  "ung thu phoi cua chu co di can chua",
  "hoa tri xong me co tai phat khong",
  "boc bai xem ca mo ngay mai cua vo anh co thanh cong khong",
  "e bi dau nguc hoai co phai benh tim khong",
  "nen chua o benh vien nao thi khoi",
  "bao gio ba duoc xuat vien",
  "thai 8 tuan chua co tim thai co giu duoc khong",
  "em co bi vo sinh khong tarot",
  "ban than toi bi lao co chet khong",
  "di toi bi lupus ban do song duoc bao lau",
  "toi bi hiv co song duoc 10 nam nua khong",
  "u xo tu cung co anh huong viec co con khong",
  "run tay cua me co phai parkinson khong",
  "ong noi bi alzheimer co nhan ra con chau nua khong",
  "mo thoat vi dia dem co bi liet khong",
  "tay gay cua con co phai mo dinh vit khong",
  "toi co nen tiem insulin khong",
  "xet nghiem viem gan b cua em co duong tinh khong",
  "co giao em bi ung thu vu co qua khoi khong",
  "sep em moi nhap vien cap cuu, xem giup sep co sao khong",
  "nguoi yeu em bi dong kinh co chua khoi duoc khong",
  "em be trong bung co bi di tat khong",
  "sinh non 32 tuan be co song duoc khong",
  "me toi co bi ung thu da day khong hay chi viem thoi",
  "tui bi zona co de lai di chung khong",
  "vay nen cua chi tiem thuoc sinh hoc co hieu qua khong",
  "cuong giap cua em uong thuoc bao lau thi khoi",
  "u tuyen giap cua me co phai ung thu khong",
  "bo em bi huyet ap cao co bi dot quy khong",
  "em bi covid lan 3 roi, co bi di chung khong",
  "ba ngoai nam liet giuong con song duoc may nam",
  "la bai noi gi ve benh tinh cua bo toi",
  "xem giup chi ket qua chup ct phoi",
  "toi nen xa tri hay phau thuat",
  "chay than roi ba co khoe lai khong",
  "polyp da day cua anh co nguy hiem khong",
  "thoai hoa cot song cua me co chua duoc khong",
  "be bi bong nuoc soi co phai ghep da khong",
  "em bi say thai 2 lan lan nay co giu duoc khong",
  "chong toi tinh trung yeu vo chong toi co con duoc khong",
  "mo mat can xong co bi mu khong",
  "anh trai em bi tam than co khoi khong",
  "u nang buong trung co can mo khong",
  "con trai toi kho khe hoai co phai hen suyen khong",
  "xet nghiem giang mai cua anh co am tinh khong",
  "benh nang lam roi, toi co song qua nam nay khong",
  "me em moi mo tim xong, me co hoi phuc tot khong",
  "mẹ e bịnh nặng lắm, mẹ có khỏi hông c",
  "a bị tiểu đường r, có hết dc ko",
  "e có bầu dc k chị ơi, cưới 3 năm r",
  "bốc giùm e 1 lá coi bịnh bao tử của e sao r",
  "ba e mổ tim mai, có ok ko ạ",
  "ông ngoại e thở máy r, ông qua dc hem",
  "tui bị bịnh gì zậy bài ơi",
  "e bị trầm cảm hả c, xem giùm e vs",
  "k bít u của mẹ lành hay ác nữa",
  "bs kêu mổ mà e sợ, mổ dc hông chị",
  "kq xét nghiệm của a có sao k",
  "bé nhà e hổng chịu nói, bé có bị j ko",
  "ck e bị xơ gan, còn sống đc mấy năm nữa",
  "vk a làm ivf lần 3 r, lần này đậu ko",
  "uống thuốc nam hết ung thư đc k nghen",
  "bà ngoại nằm viện hoài, bà có về đc hông",
  "thai e 6 tuần ra máu, giữ dc ko c ơi",
  "ba bị tai biến r, chừng nào ba đi lại đc",
  "e nên bỏ thuốc huyết áp hem, uống hoài mệt wá",
  "bịnh của dì hổng biết có qua nổi hông, coi giùm con",
  "chớ a có bị ung thư gan hông, dạo này sụt ký quá",
  "me e hoa tri dot 2 r, co dap ung ko",
  "e co bi vo sinh k c",
  "bn e bi hiv that ko",
  "Ba em bị tai biến nằm viện cả tuần nay, bói giúp em ba có qua khỏi không",
  "Mẹ mới sinh thiết hôm qua, chiều nay có kết quả, lá bài nói kết quả có đẹp không",
  "Xem bài giúp chị khối u ở vú là lành hay ác",
  "Bác sĩ trả về rồi, ông nội em còn được bao lâu nữa",
  "Em trễ kinh 10 ngày, rút 1 lá xem em có bầu không",
  "Lần chuyển phôi này có đậu không Lomi",
  "Bé nhà em 2 tuổi rưỡi chưa nói được từ nào, có sao không",
  "Chồng em lên tăng xông hoài, có nên đổi thuốc không",
  "Bói xem em có bị trầm cảm không, dạo này em chỉ muốn nằm",
  "Bà ngoại yếu lắm rồi, ăn uống không được, bà có qua được Tết này không",
  "Em nên mổ thoát vị đĩa đệm hay cứ tập vật lý trị liệu",
  "Lá bài thấy gì ở phổi của ba em",
  "Con số men gan lần này của anh có giảm không",
  "Chị bị rối loạn tiền đình mấy tháng, bao giờ thì hết hẳn",
  "Tình hình bên viện thế nào rồi, mẹ em đang nằm hồi sức",
  "Có nên cho con tiêm mũi 6 trong 1 tuần này không hay đợi",
  "Em định đi nâng mũi ở Sài Gòn, có bị biến chứng gì không",
  "Anh trai em cai rượu được 2 tháng, lần này có dứt được không",
  "Mẹ vô hoá chất đợt 3 rồi, thuốc có đáp ứng không",
  "Bói giúp em cái hạch ở cổ là gì",
  "Ba đang thở máy trong ICU, bao giờ ba cai máy được",
  "Em có nên chuyển mẹ lên tuyến trên không hay để ở bệnh viện tỉnh",
  "Xem giúp em thai lần này có giữ được không, em bị doạ sảy",
  "Con em có phải tự kỷ không, bé không nhìn vào mắt ai",
  "Ông bị nước trong phổi, hút rồi lại có, bệnh ông có nặng không",
  "Chạy tia xong thì u có teo lại không",
  "Em uống thuốc nam chữa tiểu đường có khỏi không",
  "Bài nói xem vợ em sinh thường hay phải mổ",
  "Em bị mất ngủ triền miên, có phải em bị rối loạn lo âu không",
  "Bà nội nằm một chỗ hai năm nay, bà còn ở với con cháu được bao lâu",
  "Kết quả MRI cột sống của em ngày mai có vấn đề gì không",
  "Mẹ em có nên thay khớp gối không, mẹ 68 tuổi rồi",
  "Rút 1 lá xem bệnh gút của ba có chữa dứt được không",
  "Em bị đau thần kinh toạ, châm cứu hay tiêm thì hợp hơn",
  "Hai vợ chồng cưới 4 năm chưa có con, là do em hay do chồng",
  "Bé sinh non 32 tuần đang nằm lồng ấp, con có ổn không",
  "Dạo này ba hay quên, hỏi rồi lại hỏi, ba có bị lẫn không",
  "Xét nghiệm máu sáng nay của em có ra gì xấu không",
  "Chị dâu em trở bệnh đêm qua, lần này có nguy không",
  "Em có nên ngưng thuốc huyết áp để uống lá cây theo lời hàng xóm",
  "Bói xem em gái có vượt qua được ca ghép thận không",
  "Bác em bị K gan giai đoạn cuối, có phép màu nào không",
  "Em bị gai cột sống, mổ có hết đau không hay liệt",
  "Sau đợt Covid em khó thở mãi, phổi em có bị gì không",
  "Cháu bị sốt xuất huyết ngày thứ 5, tiểu cầu có lên lại không",
  "Xem bài con trai em tăng động hay chỉ là hiếu động thôi",
  "Em nội soi ra HP dạ dày, uống kháng sinh đợt này có sạch không",
  "Mắt mẹ mổ cườm xong có nhìn lại rõ không",
  "Bầu 36 tuần mà nước ối ít, em bé có sao không",
  "Ông ngoại ngã gãy cổ xương đùi, ông có đi lại được nữa không",
  "Em có nên bỏ thai không, siêu âm bác sĩ nói tim thai yếu",
  "Lá bài cho biết nốt ruồi này có phải ung thư da không",
  "Em trai đi cai nghiện ma tuý về được nửa năm, có tái nghiện không",
  "Mẹ bị suy thận độ 3, bao lâu nữa thì phải chạy thận",
  "Em bị máu nhiễm mỡ, không uống thuốc chỉ ăn kiêng thì có xuống không",
  "Bé 4 tháng chưa biết lẫy, bé có chậm phát triển không",
  "Bói giúp anh, đau ngực trái mấy hôm nay là bệnh gì",
  "Cô em hôn mê ba ngày rồi, cô có tỉnh lại không",
  "Em nên đẻ ở Từ Dũ hay bệnh viện tư thì mẹ tròn con vuông",
  "Bác sĩ bảo theo dõi thêm cái nhân tuyến giáp, nó có to lên không",
  "Em trai bị động kinh từ nhỏ, lớn lên có tự hết không",
  "Mẹ chồng bị đột quỵ lần hai, có liệt nửa người luôn không",
  "Em chích filler môi chỗ quen, có an toàn không Lomi",
  "Bạn em hay nói muốn biến mất, bạn ấy có ý định tự tử thật không",
  "Anh bị vảy nến chục năm nay, đổi sang thuốc sinh học có khỏi không",
  "Bói xem ba em có dậy được sau ca đặt stent không",
  "Em bị đa nang buồng trứng, có con tự nhiên được không",
  "Ngoại em chắc sắp về với ông bà rồi phải không, mấy bữa nay ngoại không ăn gì",
  "ba minh bi tai bien nam mot cho, co di lai duoc khong",
  "boi giup em co bau chua, que 1 vach mo",
  "me em dang vo hoa chat, benh co lui khong",
  "ket qua sinh thiet chieu nay ra co dep khong",
  "ong noi duoc bac si tra ve hom qua, ong con duoc may ngay",
  "be nha chi 3 tuoi chua noi, co phai cham noi khong",
  "em co nen mo ruot thua noi soi hay mo ho",
  "rut 1 la xem khoi u trong gan cua chu la lanh hay ac",
  "chong em di kham vo sinh, ket qua tinh dich do co on khong",
  "xem bai em bi gi ma sut 6 ky trong 1 thang",
  "ba ngoai nam ICU 5 ngay roi, ba co qua khoi khong",
  "dot IUI nay co thanh cong khong lomi",
  "me co nen doi bac si dieu tri khong, chua hoai khong bot",
  "em test covid 2 vach, may ngay nua thi am tinh",
  "con em hay dap dau vao tuong, be co bi tu ky khong",
  "bac em len tang xong mau nga ngoai san, co bi liet khong",
  "la bai thay gi o da day cua em",
  "em co nen uong thuoc tram cam bac si ke khong hay tu vuot qua",
  "tinh hinh ben vien sao roi, ba dat noi khi quan tu toi qua",
  "thai 12 tuan do mo da gay 3.2, con em co bi down khong",
  "anh hai cai ma tuy lan 3 roi, lan nay co bo duoc khong",
  "boi xem me em song duoc bao lau nua, K phoi di can xuong",
  "em nen sinh mo hay sinh thuong cho an toan",
  "cai hach o nach cua em co nguy hiem khong",
  "chay tia 30 mui xong co tai phat khong",
  "em hay nghe tieng noi trong dau, em co bi tam than phan liet khong",
  "chau 18 thang chua biet di, co sao khong lomi",
  "ba bi soi than 2 ben, tan soi hay uong thuoc nam",
  "em co nen tiem vac xin HPV khong, so tac dung phu",
  "ket qua PCR lao cua em mai co am tinh khong",
  "me chong yeu lam roi, an uong khong duoc, co nen dua ra ha noi chua",
  "hut mo bung o tham my vien do co nguy hiem tinh mang khong",
  "boi cho em duong huyet lan tai kham nay co on khong",
  "vo em mang song thai, hai be co khoe manh den luc sinh khong",
  "chu ut tho may tuan nay, co cai duoc may khong",
  "em nen chua viem gan B bang tay y hay thuoc bac",
  "xem bai coi ba toi con tinh lai khong, hon me sau tai nan",
  "em say thai 2 lan roi, lan nay co giu duoc khong",
  "chi bi u xo tu cung 5cm, cat hay de theo doi",
  "con gai em 9 tuoi da co kinh, co phai day thi som khong",
  "ong ngoai lan roi khong nhan ra ai, ong co nho lai duoc khong",
  "dau bung duoi ben phai 2 ngay nay la bi gi vay",
  "em bi mat ngu 3 thang, co nen uong thuoc ngu khong",
  "ba bi gai cot song chen day than kinh, tap yoga co khoi khong",
  "em trai nghien da 2 nam, dua di trai cai co bo duoc khong",
  "xet nghiem HIV sau 3 thang cua em co am tinh khong",
  "me mo tim ho ngay kia, ca mo co thanh cong khong",
  "chi em vo oi som 30 tuan, be co nuoi duoc khong",
  "mau nhiem mo voi gan nhiem mo do 2 thi bao lau het",
  "ba em khong qua duoc dem nay phai khong lomi",
  "em bi tre kinh 2 thang ma que am tinh, em bi benh gi",
  "noi sap di xa roi phai khong lomi, bac si tra ve tu thu hai",
  "bói dùm e bịnh của má có hết hông",
  "e bị trễ 2 tuần r, có dính bầu ko z",
  "ba e nằm bv cả tháng, bs nói ko chắc, ba có qua đc ko",
  "kq xn máu chiều nay ra có ok ko lomi",
  "bé nhà e 2t chưa nói j hết, có bị sao hem",
  "e có nên mổ mắt cận ko hay để v",
  "ông nội yếu lắm r, chắc ko qua khỏi đợt này hả lomi",
  "xem dùm tui uống thuốc bắc ông lang trên Đức Trọng có hết viêm xoang hông",
  "mẹ bị K vú gđ 2, hoá trị xong có khỏi hẳn ko",
  "e bị j mà cứ đau đầu buồn nôn hoài zậy",
  "tui tính đi cắt bao tử giảm cân, có nguy hiểm hông nghen",
  "e có bị trầm cảm sau sinh ko, cứ khóc suốt à",
  "má tui bị tiểu đường chích insulin, giờ chuyển qua uống thuốc nam đc hông",
  "bà e trở bịnh hồi hôm, giờ ntn r lá bài",
  "e đang canh trứng, tháng này có đậu thai ko",
  "con e bị co giật lúc sốt, sau này có ảnh hưởng não ko z",
  "ổng bị xơ gan cổ trướng r, còn sống đc mấy năm nữa",
  "bs kêu mổ u nang buồng trứng mà e sợ quá, mổ hay ko mổ",
  "rút 1 lá coi thằng nhỏ nhà tui có bị chậm phát triển hông",
  "tui bị nhức khớp gối quài, chích chất nhờn có đỡ hông",
  "e xài thuốc giảm cân trên mạng, có hại gan thận ko ta",
  "mai nội soi đại tràng r, có polyp hay j ko lomi",
  "bé bị vàng da sơ sinh, chiếu đèn có hết ko hay phải thay máu",
  "e định tiêm botox gọn hàm, có bị cứng mặt ko nha",
  "ổng nhậu quá trời, gan ổng còn xài đc hông",
  "e bị rối loạn lưỡng cực hay chỉ là tính thất thường z",
  "dì út bị ung thư cổ tử cung, xạ trị xong sống đc bn năm",
  "mẹ chồng e bị tai biến lần 2, lần này có đi luôn ko",
  "e chích ngừa dại trễ 2 ngày có sao hông",
  "thằng em nghiện cỏ mới đi cai về, lần này bỏ đc hẳn ko",
  "Mẹ em mổ tim hở tuần sau, bài nói giúp em ca mổ có suôn sẻ không",
  "Bố mình đặt stent xong vẫn hay tức ngực, liệu có bị tái hẹp mạch vành không",
  "Bệnh viện trả ba em về nhà rồi, ba còn ở với tụi em được mấy ngày nữa",
  "Cái cục cứng cứng dưới nách em sờ thấy tuần trước là thứ gì, có đáng sợ không",
  "Hóa trị đợt 4 rồi mà tóc rụng hết, người mệt lả, em có nên xin bác sĩ cho ngưng không",
  "Ông ngoại bị tai biến nằm liệt nửa người, bao giờ ông đi lại được",
  "Dạo này tay em run, hay quên trước quên sau, có khi nào Parkinson sớm không",
  "Con trai em 4 tuổi chưa nói được câu nào, bé có bị tự kỷ không",
  "Em bị thoát vị đĩa đệm L4 L5, nên mổ hay tập vật lý trị liệu",
  "Thay khớp háng cho bà nội 82 tuổi thì bà có chịu nổi cuộc mổ không",
  "Vảy nến của em có hết hẳn được không hay phải sống chung cả đời",
  "Nốt ruồi trên lưng tự nhiên to ra và ngứa, có đáng lo không",
  "Mổ cận Lasik có an toàn với mắt em không, sau này có bị mờ lại không",
  "Ba em bị glôcôm, mắt trái gần như không thấy gì, mắt phải có giữ được không",
  "Em bị ù tai cả tháng nay, có khi nào điếc luôn không",
  "Bác sĩ dặn cả nhà chuẩn bị tinh thần cho bà, vậy là hết hy vọng thật hả Lomi",
  "Nhổ 4 cái răng khôn một lần có nguy hiểm gì không Lomi",
  "Em sắp phẫu thuật hàm hô, làm xong có bị biến chứng tê môi không",
  "Đau thượng vị cả tháng, ăn vào là ói, em bị gì vậy",
  "Kết quả nội soi đại tràng ngày mai của em có ổn không",
  "Chồng em chạy thận ba năm rồi, anh ấy còn trụ được bao lâu nữa",
  "Em muốn hiến một quả thận cho anh trai, ca ghép có thành công không",
  "Chuyện là mẹ em đi khám tổng quát ở công ty, người ta gọi lại bảo chụp thêm nhũ ảnh, có gì xấu không Lomi",
  "Viêm gan B của em sau này có chuyển thành ung thư không",
  "Tiểu đường tuýp 2, em bỏ thuốc tây chuyển qua uống lá cây được không",
  "Bướu cổ của mẹ có cần cắt không hay để yên cũng được",
  "Con gái em lên cơn hen liên tục, lớn lên bé có khỏi không",
  "Ba hút thuốc 30 năm giờ ho ra máu, có phải phổi ba có vấn đề nặng không",
  "Bé nhà em sốt xuất huyết ngày thứ 5, tiểu cầu tụt, con có qua khỏi không",
  "Em lỡ quan hệ không an toàn, xét nghiệm HIV sắp tới ra sao",
  "Đứa nhỏ trong bụng em ra đời có lành lặn đủ đầy không",
  "Thai 12 tuần đo độ mờ da gáy cao, con em có bị Down không",
  "Em chuyển phôi lần thứ ba, lần này có đậu không",
  "Em nên sinh thường hay sinh mổ thì an toàn cho hai mẹ con",
  "Con em sinh non 30 tuần đang nằm lồng ấp, bé có sống được không",
  "Em bé nhà em 2 tháng tuổi vàng da mãi không hết, có sao không",
  "Bà nội dạo này lẫn, không nhận ra con cháu, bà còn ở với nhà mình được bao lâu",
  "Ông em 90 tuổi bỏ ăn mấy hôm nay, có phải ông sắp đi rồi không",
  "Em khóc mỗi đêm, không muốn làm gì hết, em có bị trầm cảm không",
  "Em nghe thấy tiếng nói trong đầu, em bị tâm thần phân liệt hả",
  "Thằng em đi cai ma túy đá về được 3 tháng, nó có tái nghiện không",
  "Chồng em nghiện rượu nặng, lần này anh ấy có bỏ hẳn được không",
  "Em bị yếu sinh lý từ sau khi cưới, có chữa được không",
  "Em muốn nâng ngực, đặt túi có biến chứng gì không",
  "Hút mỡ bụng ở thẩm mỹ viện gần nhà có an toàn không, em sợ lắm",
  "Bạn em bị tai nạn xe máy đang hôn mê trong phòng hồi sức, nó có tỉnh lại không",
  "Ba bị bỏng nặng 40 phần trăm cơ thể, ba có vượt qua không",
  "Bác sĩ hẹn thứ sáu có kết quả sinh thiết hạch, em hồi hộp quá, tin lành hay tin dữ",
  "Chụp MRI não thấy có đốm trắng, cái đó là gì vậy",
  "Nên cho mẹ chuyển lên Chợ Rẫy hay để điều trị ở bệnh viện tỉnh",
  "Em có nên tiêm vắc xin HPV không, nghe nói có tác dụng phụ",
  "Con em bị động kinh, uống thuốc hoài, sau này bé có hết giật không",
  "Bé nhà em 7 tuổi hiếu động quá cô giáo nói đi khám, con có bị tăng động giảm chú ý không",
  "Em bị zona thần kinh ngay mắt, có để lại di chứng không",
  "Lupus ban đỏ có sống được lâu không Lomi",
  "Em chích thuốc giảm cân mua trên mạng được hai tuần thì tim đập nhanh, có nên chích tiếp không",
  "Sỏi thận 8 li, tán sỏi hay uống thuốc nam cho ra",
  "Mẹ em gãy cổ xương đùi, tuổi này xương có liền lại không",
  "Bác sĩ bảo cắt túi mật, em hoãn lại được không",
  "Mấy hôm nay em đi cầu ra máu, có phải trĩ thôi không hay cái gì ghê hơn",
  "Em mất ngủ triền miên phải uống thuốc ngủ, uống lâu dài có sao không",
  "Bố vừa lên cơn đau ngực dữ dội đang đưa đi cấp cứu, bố có sao không",
  "Em bị chó cắn hôm qua chưa chích ngừa, có lên cơn dại không",
  "Ung thư cổ tử cung giai đoạn 2, xạ trị xong em có sống thêm được 5 năm không",
  "Con bé nhà em 15 tuổi nhịn ăn, gầy rộc, có phải chán ăn tâm thần không",
  "Chị em bị sảy hai lần rồi, lần mang bầu này có giữ được không",
  "Vợ chồng em cưới 5 năm chưa có con, là do em hay do anh ấy",
  "Cháu nội bị thông liên thất bẩm sinh, lỗ thông có tự đóng không hay phải mổ",
  "me em bi ung thu phoi giai doan cuoi, con bao nhieu thoi gian nua",
  "ket qua sinh thiet tuyen giap cua em co phai ac tinh khong",
  "em bi dau dau mot ben suot, co phai u nao khong",
  "ba em huyet ap len 200 moi nhap vien, co bi dot quy khong",
  "suy tim do 3 thi song duoc bao lau",
  "em co nen mo day chang cheo dau goi khong hay de tu lanh",
  "mun trung ca boc day mat, uong isotretinoin co nen khong",
  "ong noi mo duc thuy tinh the hai mat, mo xong co nhin ro lai khong",
  "be nha em viem tai giua hoai, sau nay co bi anh huong nghe khong",
  "trong implant 3 cai rang co bi dao thai khong",
  "em bi trao nguoc da day 2 nam roi, co khoi dut diem duoc khong",
  "viem ruot thua ma khong mo co sao khong",
  "creatinin cua ba len cao, ba co phai chay than khong",
  "chong em gan nhiem mo do 2 van nhau, gan co hong luon khong",
  "em bi buong trung da nang, sau nay co con duoc khong",
  "tuyen giap co nhan 1cm, co can choc hut khong",
  "me bi lao phoi dang uong thuoc thang thu 2, co lay cho ca nha khong, co het han khong",
  "em bi covid keo dai kho tho hoai, phoi co phuc hoi khong",
  "em di xet nghiem giang mai, ket qua co sach khong",
  "thai 8 tuan chua co tim thai, con em co con khong",
  "tinh trung yeu thi co con tu nhien duoc khong",
  "em bau 36 tuan nuoc oi it, co phai mo som khong",
  "con em 18 thang chua biet di, co bi bai nao khong",
  "ba ngoai 85 tuoi te gay xuong chau, ba co ngoi day lai duoc khong",
  "em hay hoang so tim dap nhanh kho tho, co phai roi loan lo au khong",
  "anh trai em roi loan luong cuc, ngung thuoc duoc chua",
  "ban em dang o trung tam cai nghien heroin, ra roi no co sach han khong",
  "ong xa em 58 tuoi dao nay di tieu dem 5 6 lan lai tieu rat, la bi sao vay",
  "xuat tinh som co phai benh khong, co chua duoc khong",
  "cat mi mat o spa co bi hong mat khong",
  "tiem filler mui co bi hoai tu khong, em co nen lam khong",
  "chau em bi duoi nuoc dang tho may, chau co tinh lai khong",
  "em bi ong dot sung ca mat kho tho, co nguy hiem tinh mang khong",
  "ket qua chup CT phoi ngay kia cua ba em nhu the nao",
  "hom qua di hien mau nguoi ta goi lai noi mau em co van de, em bi gi vay",
  "em co nen doi bac si khac khong, uong thuoc 3 thang khong do",
  "co nen cho con chich ngua soi khong hay doi lon them",
  "dong y bam huyet co chua duoc dau than kinh toa cua em khong",
  "em bi roi loan tien dinh chong mat hoai, bao gio het",
  "chong em bi gut nang, khop co bi bien dang khong",
  "be bi chan tay mieng sot cao 3 ngay, co bien chung nao khong",
  "em sut 7 ky trong 2 thang khong ro ly do, trong nguoi em dang co gi",
  "me em sau mo cat da day, me con an uong binh thuong lai duoc khong",
  "ba em lu lan tu sau khi ba mat, co phai alzheimer khong",
  "em hay nghi den chuyen chet, em co bi lam sao khong",
  "noi hach o co 2 thang khong xep, co phai lymphoma khong",
  "em bi thieu mau thalassemia, lay chong sinh con co bi di truyen khong",
  "con trai em day thi som, tiem thuoc ham co anh huong chieu cao khong",
  "vet mo de cu cua em dau lai, mang bau lan 2 co vo tu cung khong",
  "ba dang nam ICU vi nhiem trung mau, gia dinh co nen chuan bi tinh than khong",
  "em moi chia tay xong lai phat hien co thai 6 tuan, giu hay bo day lomi",
  "cai u xo tu cung 5cm cua em co phai cat bo tu cung khong",
  "bả nhà tui bịnh tiểu đường mà hổng chịu kiêng, chưn bả có bị cưa hông",
  "tía tui nhậu riết giờ bụng chướng da vàng, ổng còn sống đc bao lâu",
  "má tui đi mổ mắt cườm bữa thứ 5, mổ xong má thấy đường lại hông",
  "nhỏ em tui có bầu 5 tháng mà bị ra huyết, đứa nhỏ có sao hông",
  "mạ tui đau khớp gối đi khôn nổi, mổ thay khớp có nên khôn",
  "răng mà tui ho cả tháng ni khôn hết, phổi tui có bị chi khôn",
  "ba tui nằm viện ở Huế rứa mà bác sĩ nói chuyển ra Hà Nội, đi hay ở lại tốt hơn hè",
  "e bị trễ kinh 2 tuần r, thử que 1 vạch mờ mờ, e có dính bầu k",
  "e đau bụng kinh dữ dội, đi siêu âm bs ns lạc nội mạc tử cung, có ảnh hưởng đẻ con k",
  "bn e bị ngất trong lớp, đang chờ kq điện não, có bị j nặng k",
  "sáng ngủ dậy e bị méo miệng, mắt nhắm ko kín, bao h ms hết",
  "e bị rụng tóc nhìu lắm, hói từng mảng lun, có mọc lại dc k",
  "mn ơi e nổi mề đay cả tháng r uống thuốc ko đỡ, bh ms khỏi",
  "bố em bị xơ phổi, bác sĩ bảo khó, thế bố em có qua được Tết này không nhỉ",
  "u em bị thoái hóa cột sống đau lắm, tiêm thuốc vào khớp có nên không nhỉ",
  "ông em nằm viện Bạch Mai cả tháng rồi, thở oxy suốt, thế ông có về được nhà không",
  "ck e bị giãn tĩnh mạch thừng tinh, mổ r có con dc k",
  "e 19t bị cong vẹo cột sống, đeo nẹp có thẳng lại dc k hay phải mổ",
  "e bị rối loạn ăn uống, ăn xong lại móc họng, e có tự hết dc k",
  "bé nhà e 3t bị lác mắt, mổ có hết k hay lớn tự hết",
  "thg bạn e chơi ke bị ngáo phải đi viện tâm thần, nó có bình thường lại dc k",
  "e uống thuốc tránh thai khẩn cấp 2 lần 1 tháng, sau này có vô sinh k",
  "bà ngoại tui bịnh suy thận, mấy cô chú đòi đưa bà đi thầy lang bốc thuốc, có nên hông",
  "ổng bị xuất huyết não mổ rồi mà chưa tỉnh, ổng có mở mắt lại hông",
  "em tui té xe gãy xương hàm, mổ nẹp vít xong mặt có lệch hông",
  "con tui bị sứt môi hở hàm ếch, mổ xong sau này có nói được bình thường hông",
  "mệ tui già rồi ăn chi cũng nghẹn, có phải trong cổ có cái chi khôn lành khôn",
  "chị tui đi niềng răng mà bs nói phải mổ hàm, có nên mổ khôn hay thôi",
  "e bị ám ảnh rửa tay cả trăm lần 1 ngày, e bị OCD đúng k, có chữa dc k",
  "bạn e bị bạch cầu cấp đang chờ ghép tủy, bạn ấy có tìm dc ng cho phù hợp k",
  "Dạo này ba em hay quên đường về nhà, có bữa đứng ngay đầu hẻm mà hỏi nhà mình ở đâu, ba có sao không ạ",
  "Con bé nhà em cứ ngất hoài ở trường, rút lá coi nó bị gì vậy",
  "Sáng nào ngủ dậy em cũng ói, bài nói em đang bị sao",
  "Mẹ đi tiểu đêm 5 6 lần, có phải trong người mẹ đang có gì xấu không",
  "Tay ông nội run cầm đũa không nổi nữa, ông còn ở với con cháu được bao lâu",
  "Thằng em nói ngọng từ hôm té xe tới giờ, liệu nó có trở lại bình thường không",
  "Ngực trái cứ nhói nhói mấy tuần nay, xem giúp em có nguy hiểm không",
  "Ba tháng tụt 8 ký mà ăn uống vẫn vậy, trong người em đang có chuyện gì",
  "Máu cam chảy hoài không dứt, lá bài thấy gì về cơ thể con trai em",
  "Trễ kinh 2 tháng rồi, em có dính bầu không",
  "Que lên 2 vạch mà vạch mờ lắm, rốt cuộc là có hay không hả Lomi",
  "Bụng bầu tụt hẳn xuống mà mới 34 tuần, bé có ra sớm không",
  "Mấy bữa nay em bé ít đạp hẳn, con trong bụng em có ổn không ạ",
  "Chọc ối xong đang ngồi chờ, kết quả sẽ tốt hay xấu",
  "Double test báo nguy cơ cao, con em sinh ra có lành lặn không",
  "Mổ thay van hay cứ để vậy uống cầm chừng, chọn cái nào cho ba",
  "Mẹ em vô viện từ thứ hai, sáng nay bác sĩ kêu cả nhà ra hành lang nói chuẩn bị tinh thần, em hỏi bài mẹ có qua được đêm nay không",
  "Có nên báo anh em ở xa về gấp không, ngoại thở oxy ba ngày rồi",
  "Nhà em tính xin cho bà về nhà, bà còn được mấy hôm nữa",
  "Ông ăn qua ống cả tháng nay, liệu có ngày ông tự nuốt lại được không",
  "Xạ thêm 10 tia nữa hay dừng ở đây, bài khuyên em thế nào",
  "Chị em đẻ xong băng huyết, giờ người ta hỏi chuyển xuống Chợ Rẫy hay qua Hoàn Mỹ, đường nào chị dễ qua hơn",
  "Em không muốn dậy nữa, sáng nào cũng nằm nhìn trần nhà, em bị làm sao thế",
  "Nó nói chuyện một mình suốt trong phòng, con trai tôi có bị gì trong đầu không",
  "Mấy đêm liền nghe tiếng ai gọi tên trong đầu, tôi đang mắc chứng gì",
  "Chồng em đặt máy tạo nhịp tuần sau, ca đó có suôn sẻ không",
  "Bó bột sáu tuần rồi mà bàn chân vẫn tím ngắt, xương có liền nổi không",
  "Soi cổ tử cung thấy có vết, lần bấm sinh thiết này ra lành hay ác",
  "Đo loãng xương ra âm 3 phẩy mấy, năm nay mẹ có bị gãy cổ xương đùi không",
  "Truyền đạm cho bà có giúp bà khoẻ lại không hay chỉ tốn tiền",
  "Bé đang sổ mũi mà tới lịch chích ngừa 6 trong 1, chích luôn có sao không",
  "Nâng mũi ở spa người quen giới thiệu có an toàn không hay dễ hoại tử",
  "Ba em uống thuốc tây hai năm không bớt, giờ có người chỉ ông lang trên Lạc Dương bốc lá, bỏ hẳn thuốc tây theo ông đó thì đúng hay sai",
  "Con hai tuổi rưỡi chưa nói được chữ nào, gọi không quay lại, bé có bị tự kỷ không",
  "Anh hai cai rượu lần thứ ba, lần này có dứt hẳn không",
  "Bà nội 89 tuổi dạo này không nhận ra con cháu, bà còn minh mẫn lại được không",
  "Vợ em chuyển phôi hôm thứ ba, đợt này có đậu không",
  "Sảy hai lần rồi, lần mang thai này em có giữ được con không",
  "Bác sĩ hẹn mổ đẻ ngày 20 nhưng em muốn đẻ thường, cách nào ít rủi ro cho con hơn",
  "Chụp phim thấy một đám mờ ở phổi phải, đó là cái gì vậy",
  "Vết mổ của ba cứ rỉ nước vàng, có phải nhiễm trùng không Lomi xem giùm",
  "Men gan cao gấp ba, gan chồng em có hồi lại được không",
  "Ông xã đau đầu dữ dội rồi nhìn một thành hai, có khi nào có gì trong não không",
  "Nằm ICU ngày thứ chín chưa tỉnh, cậu em có tỉnh lại không",
  "Ông mệt quá nên cả nhà tính ngưng lọc máu, làm vậy có nên không",
  "Em uống ba viên mới ngủ được mỗi đêm, bỏ hẳn được không hay lệ thuộc cả đời",
  "Bé sốt cao co giật hai lần trong tháng, sau này có ảnh hưởng trí não không",
  "Cục trong ngực chị cả 2 phân, bài cho biết lành hay dữ",
  "Tiêm filler cằm xong sưng lệch một bên, có tự hết không hay phải rút ra",
  "Thằng bé 14 tuổi suốt ngày lấy dao lam rạch tay, nó bị trầm cảm hay chỉ làm màu",
  "Mẹ em vô đợt bốn, tóc rụng hết rồi, đợt này cơ thể mẹ có đáp ứng không",
  "Tim thai yếu lúc 7 tuần, thai có phát triển tiếp không",
  "Ba em hút thuốc lào ba chục năm giờ khạc ra máu, có phải cái bệnh đó không",
  "Bạn trai em chơi đá hai năm, giờ vô trại, ra rồi ảnh có tái lại không",
  "Em tính cho em trai một quả thận, ca ghép có thành không",
  "Mắt trái tự nhiên có màn đen che nửa dưới, em có mù không",
  "Đi ngoài phân đen cả tuần, lá bài có thấy gì trong bụng em không",
  "Cháu ngoại sinh non 29 tuần đang nằm lồng ấp, bé có nuôi được không",
  "Nên cho mẹ mổ cột sống ở Sài Gòn hay ra Huế, chỗ nào hợp với mẹ hơn",
  "Bà hàng xóm bày giảm liều insulin cho đỡ mệt, em làm theo có được không",
  "Chồng 42 tuổi đêm ngủ ngưng thở từng chặp, ảnh có đột quỵ trong giấc ngủ không",
  "Đốt sóng cao tần hay cắt nửa tuyến giáp, cách nào khỏi hẳn",
  "Thứ sáu mới có kết quả sinh thiết, em có nên chuẩn bị cho tin xấu không",
  "Nội soi dạ dày ra HP dương tính, uống đủ phác đồ có sạch khuẩn không",
  "Hai vợ chồng thả năm năm chưa đậu thai, trục trặc nằm ở em hay ở ảnh",
  "Chồng em thắt rồi giờ đi nối lại, tụi em còn có con được không",
  "Ông ngoại ngã trong nhà tắm xong nằm một chỗ, ông có đi lại được nữa không",
  "Dì út méo miệng liệt nửa người, tập bao lâu thì dì tự cầm muỗng được",
  "ba e dao nay di hay va vao tuong, noi cham han di, co bi gi khong lomi",
  "me nam mot cho 2 thang roi, con kip dua me ve que khong",
  "sang nay ho ra cuc mau dong, e so qua, e co bi nang khong",
  "tre 12 ngay roi thu que 1 vach, vay co bau khong ta",
  "be nha minh 4 thang chua lay, co cham phat trien khong",
  "nen mo mat lasik hay deo kinh tiep, bai chon dum",
  "em gai uong 20 vien roi nam im, gio dang rua ruot, no co qua khoi khong",
  "chong minh bi tra ve roi, con nuoc con tat, co nen chay thay o Di Linh khong",
  "ket qua NIPT 2 tuan nua moi co, con minh co bi down khong",
  "chich mui hpv luc dang toi thang co hai gi khong",
  "chan ba sung to, an lom khong len, la tai than hay tai tim vay",
  "dau bung duoi ben phai tu toi qua, phai mo hay de tu het",
  "con trai 9 tuoi van dai dam moi dem, no co van de gi ve than kinh ha",
  "ong xa di kham ve giau to giay, to do ghi dieu gi xau phai khong",
  "di ut nam hoi suc tuan thu hai, rut ong tho duoc chua",
  "cat 2/3 da day xong me song duoc bao nam nua",
  "minh ngu co 3 tieng moi dem ca nam nay, dau oc lo mo, quen ca ten dong nghiep, minh sap hong nao chua",
  "thay khoe roi nen bo thuoc huyet ap, lam vay duoc khong",
  "thang ban than dap da may nam, vo trai lan 2, ra co cai duoc han khong",
  "e bi ra mau giua ky, lan nay la gi day",
  "bung to nhanh ma khong phai map, so thay cuc cung, trong do la gi",
  "bac hai an khong vo, nuot nghen, nguoi rop di, bac bi sao",
  "test nhanh len 2 vach dam, kho tho tu toi, e bi nang hay nhe",
  "lan dau sinh, nen de o tram xa hay len tinh cho an toan",
  "uong thuoc nam cua thay mo co tan soi khong hay phai tan bang may",
  "mat con vang tu luc moi sinh den gio 3 tuan, co can chieu den khong",
  "chuyen la vay, vo minh sinh xong 3 thang, dem khong ngu, cu ngoi nhin con roi khoc, co lan noi muon om con di dau do, vo minh bi lam sao",
  "ong noi 91 tuoi bo an 4 ngay, sap toi luc chua",
  "moi 30 ma quen truoc quen sau, co phai lu lan som khong",
  "nho rang khon luc dang bau 5 thang co anh huong em be khong",
  "tiem botox gon ham o cho gia re, lieu co bi liet mat",
  "ba nhau moi ngay 1 lit, gio bo con kip khong hay gan nat roi",
  "dat stent xong ba toi co song khoe them 10 nam khong",
  "mang doi ma 1 be ngung tim, be con lai co giu duoc khong",
  "chau bi cho can chua chich, 10 ngay roi con cho van song, co can chich nua khong",
  "vet bam tim tu nhien noi khap chan, mau em co van de gi",
  "nen doi bac si khac khong, ong nay chua 3 thang ma me cang yeu",
  "cho be uong khang sinh 5 ngay roi ngung som co sao khong",
  "ba noi lam nham ca dem, tay chan lanh ngat, ba sap di roi phai khong",
  "e 16t chua co kinh, co the e co bat thuong k",
  "thay boi bao dung mo, bac si bao mo gap, nghe ai",
  "trong implant xong sung ma sang tuan thu 3, co bi dao thai khong",
  "nha e co ba noi 84 tuoi, thang truoc con di cho duoc, gio nam mot cho khong chiu an, goi khong tra loi, e hoi ba con duoc bao lau",
  "khoi o co to bang trung cut, so khong dau, lanh tinh hay ac tinh",
  "chong di xet nghiem tinh trung, ket qua the nao",
  "xiu trong nha tam 2 lan tuan nay, tim minh co on khong",
  "me chong chong mat hoai, la tien dinh hay cai gi nang hon",
  "em be sinh ra nang co 2 ky 1, sau nay co khoe manh binh thuong khong",
  "chuyen ba tu vien tinh len tuyen tren luc nay co kip khong hay de yen",
  "toi nao toi cung phai uong ruou moi ngu duoc, toi thanh nghien chua",
  "di tam ly 6 thang ma van muon bien mat, toi co het duoc khong",
  "be gai 7 tuoi nguc da nhu, co phai day thi som khong",
  "mạ tui bựa ni ăn chi cũng ói ra hết, mạ có răng không bài ơi",
  "ôn nội nằm một chỗ rứa rồi, còn được mấy bữa nữa hè",
  "chừ mổ hay để rứa, bác sĩ nói tuỳ nhà, tui rối quá",
  "kể lomi nghe nè, nhỏ em tui lớp 11, dạo này ăn xong là chui vô toilet móc họng, ốm nhom ốm nhách, nó bị cái gì dạ",
  "ổng vô thuốc mới có hai toa mà xụi lơ, vô tiếp nổi hông trời",
  "má tui bị bịnh viện trả dìa rồi, má còn ở với tụi tui được nhiêu lâu",
  "e trễ kinh 3 tuần r mà sợ k dám thử, e có dính k v",
  "ck e nhậu xong ói ra máu, ổng có bị j nặng k ạ",
  "bé nhà e 18m chưa bik đi, có bị chậm k lomi",
  "mik bị mất ngủ vs tim đập nhanh hoài lun, mik bị j z",
  "u tôi dạo này lẫn lắm, gọi thằng cả ra thằng út, u còn nhớ lại được không",
  "thầy em đi giải buốt lại ra máu, thầy có phải mổ không ạ",
  "bu nằm viện huyện cả tuần chả đỡ, xin lên tuyến trên hay cứ nằm đấy",
  "dạo ni tui hay nghe ai kêu tên trong đầu, tui có bị khùng thiệt không",
  "hắn nằm lì trong buồng cả tháng không ăn không nói, hắn bị chi rứa",
  "ny e hút cỏ mỗi ngày, bỏ đc k hay hết cứu",
  "bầu 8w siêu âm chưa thấy tim thai, e có bị lưu k chị ơi",
  "mụ nội tê nửa người miệng méo xệch, chở đi chừ còn kịp không tề",
  "bả đòi chích mấy mũi trắng da ở tiệm nail, có bị gì hông ta",
  "thằng cu nhà cháu ho khò khè cả tháng, lá bài bảo nó bị làm sao thế ạ",
  "em đg uống thuốc trầm cảm mà muốn tự ngưng, đc ko",
  "bố em hôn mê sau tai nạn, bsi bảo chờ, bố có tỉnh ko ạ",
  "tía tui ổng tiểu đường mà cái chưn lở hoài hổng lành, có bị cưa hông",
  "dì tui đi xạ về ói miết, xạ nữa chịu nổi hông",
  "mẹ e đi khám ra hpv 16 ở cổ tử cung, mẹ e có bị k ko",
  "e phá 2 lần r, sau này e còn đẻ đc k",
  "ông cụ nhà tôi thở khò khè như kéo bễ, người ta bảo sắp rồi, có đúng thế không",
  "cháu nó sài đẹn mãi không lớn, cho uống thuốc cam có nên không",
  "bồ tui cắn kẹo đi bay hoài, giờ tay run lẩy bẩy, não ổng hư chưa",
  "o Hường té giếng gãy xương chậu, o có đi lại được không hè",
  "Ca mổ tim của mẹ em tuần sau có thành công không ạ",
  "Bố tôi bị tai biến nằm liệt nửa người từ hồi tháng ba, liệu có đi lại được như xưa không",
  "U xơ tử cung 4cm thì nên mổ hay để theo dõi tiếp",
  "Kết quả sinh thiết của chị gái em là lành hay ác",
  "Tôi bỏ thuốc huyết áp được chưa hay phải uống cả đời",
  "Con trai em có bị tự kỷ không, 3 tuổi rồi mà chưa nói được câu nào",
  "Vợ chồng em cưới 5 năm chưa có con, chạy chữa khắp nơi rồi, năm nay em có thai được không",
  "Bà nội em 89 tuổi dạo này lẫn nhiều lắm, bà còn minh mẫn được bao lâu nữa",
  "Sinh thường hay sinh mổ thì tốt cho em bé của em",
  "Chồng em có cai rượu được không",
  "Bác sĩ bảo ba em xơ gan giai đoạn cuối, ba em còn sống được mấy tháng",
  "Em mới cắt mí ở spa hôm kia mà mắt sưng tím, mắt em có bị hỏng không",
  "Có nên cho con tiêm vắc xin 6 trong 1 đợt này không, em sợ sốc phản vệ",
  "Tiểu đường type 2 uống thuốc nam có khỏi không",
  "Lần chuyển phôi thứ ba này em có đậu thai không",
  "Em có bị bệnh gì nặng không mà dạo này hay đau đầu chóng mặt",
  "Thuốc hóa trị có đáp ứng với ung thư phổi của anh trai em không",
  "Nên chuyển mẹ lên Chợ Rẫy hay để điều trị ở bệnh viện tỉnh",
  "Em có bị trầm cảm không hay chỉ là mệt mỏi bình thường",
  "Bé sinh non 30 tuần nhà em đang nằm lồng ấp có qua khỏi không",
  "Xét nghiệm HIV của em ngày mai sẽ ra kết quả thế nào",
  "Gia đình có nên xin cho ông ngoại về không, ông thở máy 5 ngày rồi",
  "Có nên uống thuốc ngủ bác sĩ kê không",
  "Khối u ở vú em là lành tính hay ung thư",
  "Nâng mũi sụn sườn tháng sau em có bị biến chứng gì không",
  "Chạy thận thì mẹ chồng em sống được bao lâu",
  "Tôi 52 tuổi bị thoát vị đĩa đệm L4 L5, đau lan xuống chân nửa năm nay, mổ hay châm cứu thì hơn",
  "Em trai em bị tâm thần phân liệt có trở lại bình thường được không",
  "Bệnh vảy nến của em bao giờ mới hết hẳn",
  "Em lỡ uống thuốc tránh thai khẩn cấp 2 lần trong tháng, sau này có bị vô sinh không",
  "Tim ba em sau khi đặt stent có ổn không",
  "Con gái tôi sốt xuất huyết ngày thứ 4, tiểu cầu tụt, cháu có nguy hiểm không",
  "Em có nên đổi bác sĩ điều trị cho mẹ không",
  "Mẹ con chị em có vuông tròn không, chị mang thai đôi mà bị tiền sản giật",
  "Đau dạ dày mãn tính như em liệu có chuyển thành ung thư không",
  "Anh ấy bỏ thuốc lá được 2 tháng rồi liệu có tái nghiện không",
  "Mổ đục thủy tinh thể xong mắt mẹ em có nhìn rõ lại không",
  "Tôi có nên ngừng xạ trị để về quê uống thuốc lá cây không",
  "Chậm kinh 10 ngày là em có thai rồi phải không",
  "Cháu nội tôi có bị tăng động giảm chú ý không",
  "Men gan cao gấp 3, em có bị viêm gan B không",
  "Vết mổ ruột thừa của em có bị nhiễm trùng không mà đau hoài",
  "Bà em nằm một chỗ ba tháng nay, cơm cháo không vô nữa, bà có qua được mùa đông này không",
  "Dạo này ba em quên trước quên sau, ra đường không nhớ lối về, ba em bị gì vậy",
  "Nó chơi đá hai năm rồi, giờ nó có dứt ra được không",
  "Que một vạch đậm một vạch mờ là sao ạ, em trễ hai tuần rồi",
  "Ông cụ nhà tôi còn ở với con cháu được mấy cái Tết nữa",
  "Đi dao kéo bên Hàn có an toàn cho em không",
  "Mẹ em vô nước biển ba ngày chưa tỉnh, mẹ có tỉnh lại không",
  "Cái lưng của tôi nên theo Tây hay theo ông lang bó lá",
  "Con bé nhà em cứ ngồi một mình xoay bánh xe cả ngày, gọi không quay lại, cháu có sao không",
  "Em gái em đêm nào cũng nghe có người thì thầm xúi nó làm bậy, nó bị gì vậy",
  "Chồng em ho ra máu cả tháng mà nhất định không chịu đi khám, anh ấy có bị gì nguy hiểm không",
  "Ba em vừa được đẩy vô phòng hồi sức, ba có ra được không",
  "Cục cứng cứng dưới nách em sờ thấy mấy tuần nay là gì vậy",
  "Em nên lên bàn đẻ ở nhà hộ sinh gần nhà hay ra tuyến trên",
  "Thằng em tôi có thoát được cái bình bóng cười không",
  "Người ta nói ông em sắp về với tổ tiên rồi, có đúng không",
  "Lần bơm IUI thứ hai này vợ chồng em có tin vui không",
  "Em sụt 7 ký trong một tháng dù ăn uống bình thường, em bị sao vậy",
  "Mẹ em nên cắt hay giữ lại bên ngực trái",
  "Phim chụp phổi của ba em có đám mờ nào đáng lo không",
  "Con em nên chích mũi nhắc bây giờ hay đợi qua đợt ho",
  "Em có nên ngưng mấy viên uống mỗi tối không, uống vô người cứ lờ đờ",
  "Bố em nằm đó mắt mở mà không biết gì từ sau cú ngã giàn giáo, bố có nhận ra em lại được không",
  "Sau đợt truyền thứ sáu này mẹ em có lui bệnh không",
  "Bà ngoại bỏ ăn, người teo tóp, đêm cứ gọi tên người đã mất, bà sắp đi rồi phải không",
  "Em hay tự rạch tay mỗi khi buồn, đầu óc em có vấn đề gì không",
  "Thằng con tôi vừa ở trại về, nó có đụng lại hàng trắng không",
  "Cái thai lần trước em bị lưu, lần này bé có ở lại với em không",
  "Bảy tuần rồi chưa thấy tim thai, con em có ổn không",
  "me em bi ung thu vu giai doan 2 co chua khoi duoc khong",
  "bo em mo nao hom qua gio van hon me, bo co tinh lai khong",
  "dau bung duoi ben phai may ngay nay co phai viem ruot thua khong",
  "ket qua xet nghiem mau cua em co van de gi khong",
  "vo em sinh co me tron con vuong khong",
  "co nen cho ba di mo cot song khong hay uong thuoc tiep",
  "bi da nang buong trung thi em co thai duoc khong",
  "con em bi dong kinh uong thuoc 2 nam roi, co khoi han khong",
  "benh gout cua chong toi uong thuoc bac co on khong",
  "ong noi em 92 tuoi, nam vien ca thang nay vi viem phoi, bac si noi con nuoc con tat, lieu ong co qua khoi khong",
  "em bi lo au hay tram cam vay, sao ngay nao cung khoc",
  "toi nen dieu tri o benh vien K hay vao Sai Gon",
  "tiem filler o tiem gan nha co bi hoai tu khong",
  "ket qua chup MRI nao cua me toi the nao",
  "anh hai em di cai nghien 3 lan roi, lan nay co thanh cong khong",
  "be nha em bi tim bam sinh, mo xong co song khoe duoc khong",
  "viem gan C uong thuoc moi co chua dut duoc khong",
  "em co nen bo thuoc tram cam khong vi thay do roi",
  "ba ngoai 85 tuoi gay co xuong dui co nen thay khop khong",
  "mat kinh 3 thang la em bi benh gi vay",
  "chi em sap sinh con dau long, nen sinh o benh vien nao thi an toan",
  "u tuyen giap cua em co phai ung thu khong",
  "chau toi bi bai nao tap vat ly tri lieu co di duoc khong",
  "mo can thi xong co bi tai can khong",
  "phoi bo em co sao khong, hut thuoc 30 nam gio ho nhieu lam",
  "lam IVF lan dau co thanh cong khong",
  "soi than 8mm nen tan soi hay uong thuoc",
  "me em tieu duong bien chung loet chan, co phai cat chan khong",
  "thuoc giam can mua tren mang co hai gan than em khong",
  "con gai em 14 tuoi chua co kinh, chau co binh thuong khong",
  "benh Parkinson cua ba toi co nang them khong",
  "sau khi cat tui mat em co khoe lai nhu cu khong",
  "em nen tiem ngua HPV bay gio hay doi sau cuoi",
  "anh em bi tai nan chan thuong so nao co tinh lai khong",
  "ba em con o voi tui em duoc bao lau, ba nam mot cho ca nam nay roi",
  "dao nay em hay quen, tay run, di hay vap, em bi sao vay",
  "thang ban em choi keo voi can suot, no co bo duoc khong",
  "tre 12 ngay roi ma thu chua len vach la sao",
  "ma em nen nghe ong thay lang hay nghe ben Tay y",
  "cai cuc o co em to len moi thang co phai thu du khong",
  "ong em bo an bo uong, chi nam nhin tran nha, ong sap di xa roi phai khong",
  "em be trong bung em it dap may hom nay, con co on khong",
  "con em 4 tuoi khong nhin vao mat ai, chi xep do thanh hang, chau co van de gi khong",
  "chong em dem nao cung thuc day la het roi sang khong nho gi, anh ay bi gi vay",
  "em co nen dao keo vong 1 khong, co rui ro gi khong",
  "me nam phong cach ly dac biet 1 tuan roi, me co ve nha duoc khong",
  "vo em sau sinh cu ngoi khoc, khong chiu be con, co ay bi sao vay",
  "cat hay giu cai tu cung cua em",
  "thang em toi o trung tam ve noi da sach 6 thang, no co dinh lai khong",
  "sang mai len vien lay to giay, tin tot hay tin xau",
  "em bi ra mau giua thang may lan roi co gi nghiem trong khong",
  "bac si keu gia dinh chuan bi tinh than, con phep mau nao cho bo em khong",
  "em hay nghi den chuyen bien mat khoi the gioi nay, em co bi lam sao khong",
  "nen cho ba xa truoc hay hoa truoc",
  "lan nay tha them 2 be tuyet co be nao bam khong",
  "ba toi gay rop, da vang nhu nghe, ba bi cai gi vay",
  "mẹ e bị k gan gđ cuối, mẹ e còn sống đc bao lâu ạ",
  "e có bầu ko ạ, trễ kinh 1 tuần r",
  "mổ u nang có sao k ạ, bs bảo e phải mổ mà e sợ quá",
  "ny e bị tr.cảm nặng có khỏi đc k ạ",
  "Mạ tui đau nặng nằm viện cả tháng ni, mạ có khỏe lại không rứa",
  "Ba con bị chi mà ho miết rứa, có phải lao phổi không hè",
  "Tía tui mổ bao tử bữa thứ năm có êm xuôi hông",
  "U tôi ốm liệt giường từ rằm tháng giêng, liệu u có qua khỏi được không",
  "e bj mụn nội tiết uống isotretinoin có hại gan hok",
  "kq xn máu của e có bị thiếu máu ko ta",
  "Bu em bị tiền đình uống thuốc mãi không đỡ, có nên đổi viện không",
  "Thầy tôi già yếu lắm rồi, năm nay cụ có ốm nặng không",
  "con e 18th chưa bik đi, bé có bị chậm pt ko mn",
  "Ổng xơ gan cổ trướng mà còn nhậu vậy sống nổi hông",
  "Răng mà mệ tui uống thuốc huyết áp rồi vẫn chóng mặt, có nên bỏ thuốc không hè",
  "e mún nâng ngực mà sợ biến chứng, có nên lm ko",
  "Chị Hai tui đẻ đứa thứ ba có mẹ tròn con vuông hông",
  "Cháu nó bị sốt co giật hoài, sau ni có ảnh hưởng chi tới não không",
  "a e bị tnan gãy cột sống, a có đi lại đc ko ạ",
  "Ôn tui nằm mô đau nấy, cơm không ăn nước không uống, ôn còn ở với con cháu được mấy bữa nữa",
  "e bị trễ r, 2 vạch mờ mờ, có phải dính r ko",
  "thằng e của e đập đá hít ke suốt, nó có quay đầu đc k",
  "Bả cứ nói có người theo dõi, đêm không ngủ đi quanh nhà, bả bị gì dzậy",
  "e hay nghĩ muốn bỏ đi cho xong, e có bị j ko ạ",
  "Ngoại nằm đó thở khò khè mấy bữa rày, ngoại sắp bỏ tụi con đi hả",
  "e tính qua Thái sửa lại cái mũi, có bị hư ko",
  "Thằng cu nhà tui ba tuổi rồi mà kêu không ngó, cứ nhón chân chạy vòng vòng, hắn có răng không",
  "hnay e thấy tim đập nhanh, khó thở, tay tê, e có bị sao ko mn",
  "Má con nên vô thuốc đợt nữa hay thôi về nhà cho khỏe",
  "bé trong bụng e có ổn ko, siêu âm bs nói có vấn đề mà chưa nói rõ",
  "Ông xã tui đi nhậu về là đập phá, sáng ra thề bỏ, lần ni ổng bỏ được thiệt không",
  "chj e mới gắn 2 phôi, có lên beta ko mn",
];

export const BLIND_NORMAL: string[] = [
  "Năm nay chuyện tình cảm của em thế nào?",
  "Người yêu cũ có quay lại không?",
  "Anh ấy có thật lòng với em không?",
  "Tôi có nên nhảy việc trong quý tới không?",
  "Tháng này tài chính của mình ra sao?",
  "Em thi đại học năm nay có đậu nguyện vọng 1 không?",
  "Cuối năm chuyển nhà vào Sài Gòn có thuận lợi không?",
  "Chuyến đi Nhật tháng sau có suôn sẻ không?",
  "Làm sao để gia đình em hoà thuận hơn?",
  "Bạn thân dạo này xa cách, tình bạn này còn giữ được không?",
  "Vận may tháng 11 của tôi thế nào?",
  "Mở quán cà phê ở Đà Lạt có nên không?",
  "Sếp có tăng lương cho em năm nay không?",
  "Crush có thích mình không?",
  "Bao giờ tôi gặp được người phù hợp?",
  "Anh nên đầu tư đất hay gửi tiết kiệm?",
  "Vợ chồng tôi có nên mua xe năm nay không?",
  "Du học Úc có hợp với em không?",
  "Dự án khởi nghiệp của tụi mình có gọi được vốn không?",
  "Mẹ chồng và em có hoà hợp được không?",
  "nam nay em co nguoi yeu khong",
  "cong viec moi co hop voi toi khong",
  "thang nay co nen cho ban muon tien khong",
  "a co nen to tinh voi co ay khong",
  "e thi ielts lan nay co dat 7.0 khong",
  "chuyen nha ra ha noi co on khong",
  "vo chong toi co hoa thuan lai khong",
  "bao gio toi mua duoc nha",
  "tinh duyen cua chi nam sau ra sao",
  "co nen hop tac lam an voi ban than khong",
  "nguoi ay dang nghi gi ve em",
  "tuan nay co tin vui gi ve cong viec khong",
  "chuyen di phu quoc cuoi thang co thuan loi khong",
  "e co nen nghi viec ve que khong",
  "tong quan van menh 3 thang toi cua minh",
  "Em đau đầu vì tiền quá, tháng này tài chính có khá hơn không?",
  "Anh chết mê cô ấy rồi, cô ấy có để ý anh không?",
  "Thi rớt lần này chắc ốm đòn với ba, kỳ thi lại em có qua không?",
  "Bệnh lười của mình bao giờ mới hết để lo sự nghiệp?",
  "Hai đứa cần mổ xẻ vấn đề gì để hết cãi nhau?",
  "Tiệm tạp hoá bán thêm thuốc lá có lời hơn không?",
  "Tim tan nát sau chia tay, bao giờ em yêu lại được?",
  "Sống chết gì anh cũng phải lấy cô ấy, gia đình cổ có đồng ý không?",
  "Công việc mới lương cao khỏi phải nói, nhưng em có nên nhận không?",
  "Nhà thuốc mới mở của chị có đông khách không?",
  "Em làm bác sĩ có hợp không hay nên theo kinh tế?",
  "Con gái tôi thi y dược năm nay đậu không?",
  "Bệnh viện tư anh góp vốn đầu tư có lời không?",
  "Công việc bên đó nghe bảo khoẻ re, mình chuyển qua có ổn không?",
  "Mệt mỏi vì tình quá, em có nên buông không?",
  "Đau lòng vì bị bạn thân phản bội, có nên tha thứ không?",
  "Cái dự án chết tiệt này bao giờ mới xong?",
  "Người yêu em sống ảo quá, anh ấy có nghiêm túc không?",
  "Có cách nào cứu vãn mối quan hệ này không?",
  "Sau đợt lỗ này kinh tế nhà em bao giờ hồi phục?",
  "Bao giờ gia đình tôi khỏi bệnh nghèo?",
  "Cơn sốt đất ở Bảo Lộc, mua lúc này có hớ không?",
  "Vết thương lòng này bao giờ lành để em mở lòng lại?",
  "chuyen di nay co phai lieu thuoc tinh than cho hai dua khong",
  "mo heo dat lay tien dau tu vang co nen khong",
  "e thi bac si noi tru nam nay co dau khong",
  "ban thuoc tay online co kiem duoc tien khong",
  "shop my pham cua e thang nay co dat khach khong",
  "tim dap nhanh moi lan gap crush, nguoi ta co thich minh khong",
  "sep kho tinh lam e phat om, co nen xin chuyen phong khong",
  "ny e ghen nhu dien, tinh nay co ben khong",
  "hoc duoc ra truong co de xin viec khong",
  "mo phong kham nha khoa o da lat co dong khach khong",
  "cong ty dang hap hoi, toi co nen o lai khong",
  "e me anh ay nhu dieu do, anh ay co thuong e that khong",
  "Người yêu cũ có quay lại không",
  "Tháng này em có nên nhảy việc không",
  "Crush có thích em không Lomi",
  "rut 1 la xem tuan nay cua em the nao",
  "Em nên học tiếng Trung hay tiếng Hàn",
  "bao gio em moi co nguoi yeu",
  "Mở quán cà phê ở Đà Lạt năm nay có ổn không",
  "anh ay co dang giau em chuyen gi khong",
  "Em thi đại học có đậu nguyện vọng 1 không",
  "Cuối năm có nên mua đất không hay chờ",
  "sep co y dinh tang luong cho em khong",
  "Hai đứa em cưới năm sau có hợp không",
  "Em với mẹ chồng bao giờ mới hoà thuận",
  "co nen cho ban than vay tien khong",
  "chuyen vo sai gon lam hay o lai que",
  "bói dùm e tình duyên năm nay đi",
  "Đi du học Úc kỳ tháng 2 có suôn không",
  "e voi ny cai nhau hoai, co nen chia tay ko",
  "Xem bài vận may tháng 11 của em",
  "Shop online của em khi nào mới có đơn đều",
  "toi nen hop tac voi nguoi ban cu hay lam mot minh",
  "Phỏng vấn thứ sáu này có qua không",
  "Anh ấy nhắn tin lại sau 3 tháng im lặng là có ý gì",
  "nam nay co nen xay nha khong",
  "Em gái em lấy chồng xa có hạnh phúc không",
  "Mục tiêu tiết kiệm 100 triệu năm nay có đạt không",
  "em co hop voi nghe sale khong",
  "Ba mẹ có đồng ý cho em yêu người miền Tây không",
  "dau tu vang luc nay co nen khong",
  "Bạn cùng phòng có đang nói xấu em không",
  "tet nay ve que co gap lai nguoi cu khong",
  "em nen chon nganh marketing hay ke toan",
  "Con đường sự nghiệp 5 năm tới của em ra sao",
  "khach hang lon co ky hop dong tuan nay khong",
  "Hôm nay em nên chú ý điều gì",
  "Người yêu em làm bác sĩ, ảnh có chung thuỷ không",
  "em nghien game qua, co nen theo esport luon khong",
  "Sốt vé concert tháng 12, em có săn được vé không",
  "cay phim toi sang hoai, crush co thay em nham chan khong",
  "Em đổi sang ca đêm thì lương có khá hơn không",
  "em lieu nghi viec khi chua co cho moi thi co on khong",
  "Đi Thái chơi dịp Tết với hội bạn có vui không",
  "Sinh nhật năm nay crush có nhớ không",
  "em la sinh vien nam cuoi, ra truong co viec lien khong",
  "Team em có sống sót qua đợt cắt giảm nhân sự không",
  "deadline di chet luon, sep co cho lui han khong",
  "Viện nghiên cứu nhận hồ sơ của em rồi, em có đậu không",
  "Em nhập thuốc nhuộm tóc về bán online có lời không",
  "Thương hiệu trà sữa của em có hồi sinh được sau đợt này không",
  "dem xe di kham tong the roi ban co duoc gia khong",
  "Nhà em Tết này mổ lợn ăn tất niên, họ hàng có về đủ không",
  "Cả phòng gọi em là bác sĩ tâm lý, em có nên chuyển qua làm HR không",
  "em ngop tho vi deadline, co nen xin chuyen bo phan khong",
  "Mua bảo hiểm coi như tiêm phòng rủi ro tài chính, năm nay có nên mua không",
  "kenh tiktok cua em chet view roi, co nen lam kenh moi khong",
  "Dự án đang hấp hối, đổi leader có cứu được không",
  "sep em kho tinh nhu ba de, co nen o lai khong",
  "Dự án em thai nghén 2 năm, ra mắt tháng này có thành công không",
  "Sếp bắt bệnh đúng chỗ yếu của team, em có bị đổi vị trí không",
  "cong ty em thay mau nhan su, em co tru lai duoc khong",
  "Em dị ứng với kiểu người gia trưởng, anh này có phải vậy không",
  "em hoc duoc nam 3, ra truong nen lam trinh duoc vien hay dung quay",
  "Em thi nội trú năm nay có đậu chuyên ngành mong muốn không",
  "nguoi yeu em la dieu duong truc dem suot, tui em co ben khong",
  "Ví em đang viêm màng túi nặng, cuối tháng có khoản nào về không",
  "con xe cu cua em tho oxy roi, nen sua hay ban",
  "Tụi em sống chết gì cũng đòi cưới, ba mẹ có chịu không",
  "mat ngu vi hoi hop cho ket qua phong van, em co dau khong",
  "Kết quả xét tuyển học bạ chiều nay ra có đẹp không",
  "crush em lam o vien kiem sat, anh ay co de y em khong",
  "má có chịu cho con lên Sài Gòn học không",
  "ba mẹ em cãi nhau to hôm qua, hai người có làm lành không",
  "thằng bạn thân mượn 5 triệu từ năm ngoái có trả không",
  "Năm nay em có lấy được chồng không",
  "em nen o lai cong ty cu hay nhay viec",
  "thang nay buon ban co kha hon khong",
  "em thi dai hoc co dau nguyen vong 1 khong",
  "người yêu cũ có quay lại không",
  "Chị dâu với mẹ chồng em bao giờ mới hết xích mích",
  "anh hai tui đi Nhật làm có suôn sẻ hông",
  "tui với bả có nên hùn vốn mở quán cà phê hông",
  "e vs ny cãi nhau r, ai nên xin lỗi trc",
  "bố có đồng ý cho em lấy anh ấy không nhỉ",
  "cuoi nam nay em co mua duoc nha khong",
  "em gái em có đậu phỏng vấn visa du học không",
  "sep moi co quy em khong",
  "Nên chuyển vô Đà Nẵng sống hay ở lại Hà Nội",
  "chồng em có đang giấu em chuyện gì không",
  "ban cung phong co noi xau em khong",
  "tình duyên của em 3 tháng tới ra sao",
  "e nên học thêm tiếng Trung hay tiếng Hàn",
  "lo hang sap ve co ban chay khong",
  "Ông bà nội có chịu chia đất cho ba em không",
  "con trai tui lên thành phố học có ngoan hông hay ham chơi",
  "tuan nay em co gap may man gi khong",
  "mối quan hệ của em với mẹ ruột có cải thiện được không",
  "nó có thật lòng với tui khôn hay chỉ chọc cho vui",
  "em co nen to tinh voi anh dong nghiep khong",
  "Chuyến đi Đà Lạt cuối tháng với hội bạn có vui không",
  "đứa em họ mượn xe hoài, tui có nên nói thẳng với nó khôn",
  "nam sau em co duoc tang luong khong",
  "cô bạn thân dạo này lạnh nhạt với em, tụi em có còn chơi được với nhau không",
  "kinh doanh online quan ao tre em co hop voi em khong",
  "em nen dau tu vang hay gui tiet kiem",
  "anh trai em với vợ có ly hôn không",
  "bo me co ung ho em di lam xa khong",
  "e có nên nghỉ học đh để đi làm lun k",
  "Năm nay tài lộc của em thế nào",
  "chi em co nen lay nguoi do khong, nha em ai cung phan doi",
  "Công ty em đang ốm yếu quá, năm nay có vực dậy nổi không",
  "Dự án này chết yểu hay sống được hả Lomi",
  "em co nen mo tiem thuoc tay khong, von it qua",
  "e đang học y năm 3, có nên chuyển ngành k",
  "em thi vao truong y duoc co dau khong",
  "Bé Sún nhà em có thích trường mới không",
  "toi nay hen ho voi anh ay co vui khong",
  "ho co moi em di dam cuoi khong",
  "em di thai choi 5 ngay co vui khong",
  "me cu benh thang ut hoai, bao gio me cong bang voi em",
  "he nay nen di kham pha Ha Giang hay Phu Quoc",
  "em lam bai thi co bi sot cau nao khong",
  "em ru no di choi no chi u mot tieng, no co thich em khong",
  "em xin vao vien nghien cuu kinh te co duoc khong",
  "lieu anh ay co con thuong em khong",
  "vuon cam nha em nam nay co duoc mua khong",
  "ba cam em yeu som, em co nen giau khong",
  "Em đang sốt ruột chờ kết quả phỏng vấn, có đậu không",
  "Em đau đầu vì chuyện tiền nong quá, bao giờ mới dễ thở hơn",
  "Mối tình này là liều thuốc độc hay thuốc bổ cho em vậy",
  "Em có nên mở phòng khám nha khoa riêng không hay tiếp tục làm thuê",
  "Em làm trình dược viên được 2 năm, có nên nhảy sang hãng khác không",
  "em hoc dieu duong ra truong co xin duoc viec o que khong",
  "Cơn sốt đất ở quê em có quay lại không",
  "e bị dị ứng vs sếp mới lắm, có nên xin chuyển phòng k",
  "Thị trường chứng khoán đang hấp hối, em có nên cắt lỗ không",
  "nó ghen tới phát điên luôn, tui với nó có nên tiếp tục hông",
  "em nghien tra sua qua, mo quan tra sua co hop khong",
  "bao gio em mo duoc long voi nguoi moi",
  "anh ay lanh nhu bang, trai tim anh ay co con cho cho em khong",
  "Em là bác sĩ nội trú, năm nay có nên cưới không hay đợi học xong",
  "chi em ban my pham, mo them spa co dong khach khong",
  "tiem vang cua di Sau co chiu nhan em vo lam khong",
  "Em say nắng anh hàng xóm, có nên tiến tới không",
  "Con tim em đã chết từ ngày chia tay, bao giờ em mới yêu lại được",
  "e vs nó chiến tranh lạnh cả tuần r, mệt tim ghê, ai xuống nước trc",
  "nhom em lam do an ve benh vien thong minh, co duoc giai khong",
  "ban be goi em la Ut Khung, em co nen doi ten facebook khong",
  "em moi vo lam le tan o benh vien tu, sep o do co de chiu khong",
  "Hôn nhân của em như đang nằm phòng cấp cứu, có cứu vãn được không",
  "Năm nay em có gặp được người thương không",
  "Anh ấy có còn nghĩ tới em không Lomi",
  "cong viec moi o Sai Gon co hop voi minh khong",
  "Nên nghỉ việc ngân hàng để về Đà Lạt mở quán cà phê không",
  "thang nay tien bac cua e ra sao",
  "Thi đại học năm nay em có đậu nguyện vọng 1 không ạ",
  "nyc nhắn lại sau 2 năm, có nên rep k",
  "Vợ chồng em dạo này hay cãi nhau, tụi em có vượt qua được không",
  "co nen chuyen ve o chung voi ba me chong khong",
  "Mua miếng đất ở Lâm Hà lúc này có lời không",
  "sep moi co quy minh khong ta",
  "tui với nhỏ bạn thân giận nhau cả tháng rồi, ai nên xuống nước trước",
  "Sang năm đi xuất khẩu lao động Nhật có thuận không",
  "crush co thich e k hay chi coi e la ban",
  "Em nên chọn ngành thiết kế hay kế toán",
  "tuan nay co gi vui cho toi khong",
  "Hai đứa quen nhau qua mạng, gặp ngoài đời có hợp không",
  "mo shop quan ao online cuoi nam nay co on k",
  "Ba mẹ không ưng bạn trai em vì khác tôn giáo, chuyện tụi em rồi sẽ đi về đâu",
  "khi nao minh moi het e day",
  "Hợp đồng lớn với khách bên Hàn tháng sau có ký được không",
  "chừ tui nên ở lại Huế hay vô Sài Gòn kiếm việc",
  "anh ay co dang quen ai khac sau lung em khong",
  "Homestay nhà em mùa mưa này khách có đông không",
  "xin hoc bong di Uc lan nay co cua khong",
  "Mượn tiền bạn hùn vốn bán trái cây sấy, có nên không",
  "e muon noi loi chia tay ma chua dam, bai noi sao",
  "Con gái em với bà nội nó sao cứ khắc khẩu, làm sao cho êm nhà",
  "lam freelance full time duoc chua hay van giu viec van phong",
  "Vận may của tôi quý cuối năm thế nào",
  "chuyen nha tro moi co hen khong lomi",
  "Thằng em tui tính cưới vợ tháng chạp, đám cưới có suôn không",
  "nguoi cu quay lai la that long hay chi vi co don",
  "Em có duyên làm youtuber du lịch không nhỉ",
  "dau tu vang hay gui tiet kiem nam toi",
  "bồ tui dạo này lạnh nhạt ghê, ổng hết thương tui rồi hả",
  "phong van cong ty Nhat thu 5 nay co qua khong",
  "Kỳ này em có lên được trưởng nhóm không hay lại trượt",
  "hom nay toi nen chu y dieu gi",
  "Tết này về ra mắt nhà bạn gái ở Quảng Ngãi có thuận buồm xuôi gió không",
  "Tim em loạn nhịp mỗi lần ảnh nhắn tin, ảnh có ý gì với em không",
  "Ông sếp em đầu óc có vấn đề hay sao mà toàn giao việc lúc 11 giờ đêm, em nên ở lại hay nhảy việc",
  "Team em đang hấp hối vì nghỉ gần hết, quý sau có cứu nổi doanh số không",
  "Cuối tháng đau ví quá trời, tháng sau tiền nong có dễ thở hơn không",
  "Ảnh cứ viện cớ bận để khỏi gặp, có phải ảnh đang né em",
  "Hai chị em dâu nhà em như thùng thuốc súng, Tết này về chung mâm có yên không",
  "Chồng sắp cưới của em là bác sĩ, cưới xong em có phải theo ảnh về Cần Thơ không",
  "Em gái em mới nhập học Học viện Ngoại giao, nó có trụ nổi ngoài Hà Nội không",
  "Đất Bảo Lộc đang sốt lại, ôm thêm một lô lúc này có ăn không",
  "Em học dược ra tính mở nhà thuốc ở quê, buôn bán có sống được không",
  "Công ty đang thay máu nhân sự, đợt này em có dính tên không",
  "Em say nắng anh hàng xóm mất rồi, có nên bật đèn xanh trước",
  "Vết thương lòng cũ cứ rỉ máu mỗi lần thấy ảnh đăng hình với người mới, em nên block hay cứ để vậy",
  "Quán phở nhà em ế quá, đại phẫu lại cả cái menu thì có kéo được khách không",
  "Em thai nghén bộ truyện tranh này ba năm rồi, gửi nhà xuất bản có được nhận không",
  "Chuyến đi chữa lành một mình ở Măng Đen có giúp em quên được ảnh không",
  "ổng ghen như bị điên, tui có nên quen tiếp hông",
  "Năm nay em thi bác sĩ nội trú, có đậu đúng chuyên ngành mình thích không",
  "Mẹ em làm điều dưỡng muốn em theo ngành y mà em mê vẽ, nghe mẹ hay nghe mình",
  "Sếp gọi em là liều thuốc tinh thần của cả phòng, vậy kỳ này có được tăng lương không",
  "con bạn thân tui khùng hay sao á, quay lại với thằng đó lần 3, tụi nó có bền hông",
  "du an cua tui chet lam sang 3 thang roi, co nen ban giao cho nguoi khac lam",
  "mo quan tra sua gan truong cap 3 co dong khach khong",
  "e dinh sang lai tiem toc o Duc Trong, co nen khong",
  "thang 12 di thai lan voi hoi ban co vui khong hay lai gian nhau",
  "ho hang ben noi cu soi moi chuyen dat dai, bao gio nha toi moi yen",
  "me chong luc nao cung benh vuc em chong, toi phai cu xu sao day",
  "cam on lomi hom truoc nha, gio xem tiep duong tinh duyen thang nay cho e voi",
  "lieu co nen to tinh voi anh dong nghiep khong ta",
  "hen ho voi nguoi lon hon 10 tuoi co ben khong",
  "sot ruot qua, bao gio ben cong ty moi goi di lam vay",
  "u la troi sao duong tinh toi lan dan the nay, sang nam co kha hon khong",
  "tieu tien nhu nuoc, lam sao giu duoc tui tien nam nay",
  "de xuat tang luong voi sep luc nay co on khong",
  "ung tuyen vao cong ty cu cua nguoi yeu cu co ky khong",
  "khoi nghiep o tuoi 35 co muon qua khong",
  "nen cat lo ma co phieu nay hay gong tiep",
  "30 tuoi chua chong, bao gio duyen moi toi",
  "dau dau vi no nan qua, bao gio e moi tra het",
  "bau lop truong ky nay co toi luot e khong",
  "Người yêu cũ có còn nhớ em không",
  "Em lỡ gửi nhầm tin nhắn chê sếp vào nhóm công ty, có sao không ạ",
  "Mẹ biết em tiêu hết tiền học rồi, có sao không",
  "chuyen bay sang mai co bi delay khong",
  "Giờ rút đơn nghỉ việc còn kịp không",
  "Năm nay em có lấy chồng được không",
  "anh ay co that long voi em khong hay chi choi qua duong",
  "Bố mẹ có đồng ý cho em đi du học Nhật không",
  "thang nay tien bac cua toi the nao",
  "Em nên ở lại Đà Lạt hay về Sài Gòn làm",
  "Em trai em thi đại học năm nay có đậu nguyện vọng 1 không",
  "ba ma em co lam lanh voi nhau khong",
  "Bạn thân giận em cả tuần rồi, tụi em có chơi lại được không",
  "co nen cho thang ban muon 20 trieu khong",
  "Mua đất ở Lâm Hà lúc này có hên không",
  "chi gai em lay chong xa, chi co hanh phuc khong",
  "Sếp mới có ưa em không",
  "em di phong van thu sau co duoc nhan khong",
  "Ông bà nội có chịu sang tên căn nhà cho ba em không",
  "toi nen mo quan ca phe hay tiep tuc di lam thue",
  "Chuyến đi phượt Hà Giang cuối tháng có trục trặc gì không",
  "Con gái tôi đòi cưới thằng đó, hai đứa có bền không",
  "em lo quen sinh nhat ny, co bi gian khong",
  "Tháng sau chuyển trọ, chỗ mới có hợp với em không",
  "crush có thích e ko ạ",
  "Mẹ chồng có thương em thật lòng không",
  "no nan cua vo chong toi bao gio moi tra het",
  "Em nộp học bổng trễ hai ngày, có sao không",
  "anh hai em di xuat khau lao dong co lam an duoc khong",
  "cuoi nam nay em co duoc tang luong khong",
  "Em với nhỏ bạn cùng phòng cãi nhau hoài, có nên dọn ra không",
  "Ba phát hiện em lén đi chơi xa với bạn trai rồi, có sao không",
  "Em gái tôi đi một mình vô Sài Gòn lập nghiệp, nó có ổn không",
  "chong em dao nay hay ve tre, anh co nguoi khac khong",
  "Em gái út bỏ nhà đi cả tuần, nó có chịu về không",
  "thi lai mon toan lan nay co qua khong",
  "Em có nên nói thật với ba mẹ chuyện em nợ thẻ tín dụng không",
  "Cô giáo chủ nhiệm có ghét con em không",
  "Lỡ ký hợp đồng thuê nhà mà chưa đọc kỹ, có rủi ro gì không",
  "bao gio em moi gap duoc nguoi ay",
  "Dì út với mẹ em giận nhau vì chuyện đất đai, bao giờ mới hòa",
  "em lo tay like anh nguoi yeu cu, co sao khong ta",
  "tuoi em nam nay co nen xay nha khong",
  "Đi biển Nha Trang đợt bão này có nguy hiểm gì không",
  "shop quan ao online cua em bao gio moi co khach",
  "Em lỡ làm vỡ cái bình cổ của ông nội, ông có giận lắm không",
  "Thằng bạn rủ góp vốn nuôi tôm, có nên tin nó không",
  "giờ đổi nguyện vọng còn kịp ko ạ",
  "Con trai tôi mới ra trường, nó có xin được việc gần nhà không",
  "Cuộc hôn nhân của tôi đang hấp hối, còn cứu vãn được không",
  "Dự án này chết yểu rồi hay còn hồi sinh được",
  "Em say nắng anh đồng nghiệp, có nên tỏ tình không",
  "Sốt đất Bảo Lộc đợt này có nên ôm vào không",
  "Quán phở của em đang ngắc ngoải, có nên sang lại không",
  "Anh ấy là liều thuốc tinh thần của em, tụi em có đi tới đâu không",
  "Tôi bị sếp mổ xẻ bản báo cáo trước cả phòng, sếp có ghét tôi không",
  "Em viêm màng túi cả tháng nay, bao giờ mới có tiền",
  "Em sống chết cũng muốn cưới anh ấy, ba mẹ có cho không",
  "Dính điểm liệt môn Anh thì em có rớt tốt nghiệp không",
  "Em thi vào đại học Y Dược Huế năm nay có đậu không",
  "Chị em là điều dưỡng, có nên chuyển sang bệnh viện tư để lương cao hơn không",
  "Phòng khám nha khoa của vợ chồng tôi có nên mở thêm chi nhánh không",
  "Em đang thực tập ở khoa nhi, trưởng khoa có quý em không",
  "Bạn trai em là bác sĩ nên bận suốt, tụi em có cưới được không",
  "Cửa hàng thuốc bảo vệ thực vật của ba em năm nay làm ăn sao",
  "Em bán cơm trước cổng bệnh viện có đắt hàng không",
  "Nhà em mổ heo ăn tân gia cuối tuần, tiệc có suôn sẻ không",
  "Thằng Còi lớp em có thích em không",
  "cong ty em dang thay mau nhan su, em co bi cho nghi khong",
  "tim em tan nat vi anh ay, bao gio em moi quen duoc",
  "kinh te nha em dang kiet que, nam sau co kha hon khong",
  "kenh tiktok cua em bi bop tuong tac, co song lai duoc khong",
  "mo nha thuoc tay o Duc Trong co dat khach khong",
  "em hoc duoc si hay hoc ke toan thi hop hon",
  "em xin viec o benh vien tinh co duoc nhan khong",
  "cong ty thiet bi y te no luong 2 thang, em co nen nghi khong",
  "ban em ten Thai, no co con gian em khong",
  "em di Thai choi thang sau co vui khong",
  "mo quan nhau o Lien Nghia co lai khong",
  "u em bat lay chong nam nay, em co nen nghe khong",
  "em hoc mai khong thuoc bai, thi co qua khong",
  "me chong luc nao cung benh con trai, em co song chung noi khong",
  "em bi sa thai roi, bao gio co viec moi",
  "em om hang tet nhieu qua, co ban het khong",
  "em vua cai nhau voi ma, ma co het gian khong",
  "tiem toc cua em co nen doi cho khong",
  "em mat vi tien hom qua, co tim lai duoc khong",
  "lop em bau lop truong, em co trung khong",
  "em mo thay nguoi yeu cu ba dem lien, co y nghia gi khong",
];

export const BLIND_REFLECT: string[] = [
  "Mẹ đang bệnh, anh nên giữ tinh thần thế nào?",
  "Làm sao để đối diện với giai đoạn điều trị này?",
  "Em đang chăm ba ốm, làm sao để không gục ngã?",
  "Tôi vừa nhận chẩn đoán ung thư, tôi nên giữ tâm thế nào để bước tiếp?",
  "Chăm mẹ nằm viện lâu ngày, em cần chăm sóc bản thân ra sao?",
  "Trong những ngày hoá trị, điều gì có thể làm chỗ dựa tinh thần cho mình?",
  "Chồng em bệnh nặng, em nên đồng hành cùng anh ấy bằng thái độ nào?",
  "Sống chung với bệnh mãn tính, tôi tìm ý nghĩa ở đâu?",
  "Lá bài có lời nhắn gì cho em trong lúc chăm bà đang ốm?",
  "Con bị bệnh lâu ngày, làm sao để mẹ vững vàng bên con?",
  "Mình nên học cách chấp nhận bệnh tật của bản thân như thế nào?",
  "Những ngày nằm viện này, tôi nên nuôi dưỡng điều gì trong lòng?",
  "Ba bệnh, cả nhà căng thẳng, em nên làm gì để giữ bình an cho mình?",
  "Em kiệt sức vì chăm người bệnh, em cần nhắc mình điều gì lúc này?",
  "Đang điều trị dài ngày, tôi nên trân trọng điều gì mỗi ngày?",
  "vo dang benh a nen giu vung tinh than bang cach nao",
  "lam sao de manh me khi cham ba dang om",
  "e dang dieu tri benh, e nen doi dien voi noi so nhu the nao",
  "toi can lam gi de binh tam trong thoi gian nam vien",
  "cham chong benh lau ngay, chi nen tu cham soc minh ra sao",
  "la bai khuyen em dieu gi de vung long khi me dang nam vien",
  "minh dang benh, lam sao de bot thay co don",
  "ong noi dang om nang, chau nen o ben ong voi tam the nao",
  "song voi benh tat, toi nen tim niem vui o dau",
  "giai doan nay vua di lam vua cham con om, e nen can bang tinh than the nao",
  "Em đang điều trị ung thư, làm sao để giữ tinh thần mỗi ngày",
  "Mẹ nằm viện dài ngày, em nên giữ tâm thế nào khi chăm mẹ",
  "lam sao de bot so hai trong nhung ngay cho mo",
  "Ba bệnh nặng, em nên trân trọng điều gì trong quãng thời gian này",
  "Em nên nhìn những ngày nằm viện này như thế nào cho nhẹ lòng",
  "cham ba om lau qua em met moi, lam sao de em vung hon",
  "Điều gì giúp em bình an khi sống chung với bệnh mãn tính",
  "toi nen doi dien voi noi buon ra sao khi me ngay cang yeu",
  "Lá bài nhắn gì cho em trong lúc đang chạy thận mỗi tuần",
  "Con em bệnh dài ngày, em tìm sức mạnh ở đâu để tiếp tục",
  "lam sao tim duoc y nghia trong nhung ngay nam mot cho",
  "Em nên mang thái độ gì khi đồng hành cùng chồng lúc anh ấy xạ trị",
  "khi cham ong ba gia yeu, em nen nho dieu gi de khong cau gat",
  "Giữa đợt hoá trị, em nên bám vào điều gì để không gục",
  "em bi benh tu nho, lam sao de thoi tu ti va song vui hon",
  "Làm sao để em ở bên ba trọn vẹn nhất khi ba đang ốm",
  "toi vua biet minh benh, nen bat dau chap nhan tu dau",
  "Chăm mẹ bị lẫn làm em kiệt sức, em cần học cách buông điều gì",
  "em nen noi gi voi long minh moi toi truc o vien",
  "Bệnh tật dạy em bài học gì ở giai đoạn này",
  "lam sao giu duoc hy vong ma khong tu lua doi minh khi nguoi than benh nang",
  "Em vừa nuôi con nhỏ vừa nuôi chồng bệnh, em nên thương mình bằng cách nào",
  "Trong lúc dưỡng bệnh ở nhà, em nên dành tâm trí cho điều gì",
  "song chung voi tieu duong may nam roi, lam sao de em bot chan nan",
  "Khi người thân đau mà mình không làm gì được, em nên giữ lòng mình ra sao",
  "Em đang điều trị ung thư, Lomi cho em một thông điệp để giữ vững tinh thần những ngày này",
  "Mẹ em bệnh nặng, em chăm mẹ một mình mệt lắm, em nên giữ tâm thế nào để không gục",
  "Nằm viện lâu ngày buồn quá, em nên trân trọng điều gì trong giai đoạn này",
  "minh dang cham ba bi tai bien, lam sao de minh binh tam hon moi ngay",
  "bai co loi nhan gi cho tinh than cua em trong luc dang chay than khong",
  "tui bịnh lâu rồi, hổng hỏi chuyện hết hay hông, chỉ muốn biết nên sống mỗi ngày sao cho nhẹ lòng",
  "e đang trầm cảm, đang đi trị liệu r, lá bài nhắn j cho e để e thương bản thân hơn",
  "Làm sao để em tìm được ý nghĩa khi cơ thể không còn khỏe như trước",
  "em cham ma nam mot cho hai nam nay, nhieu luc tui than qua, em nen nuong tua vao dau",
  "Trong những ngày ở bên bà cuối đời, em nên chú tâm vào điều gì",
  "Chồng em đang ốm, em muốn làm chỗ dựa cho anh, em cần nuôi dưỡng điều gì trong mình",
  "dang mang benh trong nguoi, em muon hoc cach chap nhan va song cham lai, bai khuyen em dieu gi",
  "em la con trai mot, nghi viec ve que cham bo om, lam sao de khong oan trach so phan",
  "Em sợ lắm mỗi lần vào viện, thái độ nào giúp em đối diện nỗi sợ",
  "bệnh ni theo tui lâu rồi, chừ tui chỉ muốn hỏi răng cho lòng yên thôi",
  "lam sao giu duoc niem vui nho moi ngay khi phai nam mot cho",
  "Con em bệnh mãn tính, làm mẹ em nên giữ sự kiên nhẫn và dịu dàng bằng cách nào",
  "Thông điệp nào cho người đang chăm người thân ốm như em",
  "e moi biet minh bi benh man tinh, ko hoi chuyen khoi hay ko, chi muon biet nen doi dien voi cam xuc nay ntn",
  "Em muốn biết ơn cơ thể mình dù nó đang yếu, bài gợi ý em bắt đầu từ đâu",
  "o ben ong nhung ngay nay, chau nen noi gi lam gi de sau nay khong hoi tiec",
  "suc khoe khong con nhu xua, em nen buong bo dieu gi de long nhe hon",
  "Giữa những đợt điều trị mệt mỏi, điều gì đang âm thầm nâng đỡ em mà em chưa nhìn thấy",
  "vo em dang benh, em met va cau gat hoai, em can nhin lai dieu gi o ban than",
  "Bạn em đang cai nghiện, em không hỏi kết quả, chỉ muốn biết mình nên đồng hành với bạn bằng tâm thế nào",
  "Mẹ đang hoá trị, em nên giữ tâm thế nào để ở bên mẹ cho trọn",
  "Chăm ba nằm liệt ba năm rồi, tôi lấy sức đâu để đi tiếp",
  "minh dang benh dai ngay, lam sao de khong thay minh la ganh nang",
  "Từ ngày biết mình mắc bệnh em thấy mọi thứ vô nghĩa, bài có lời nào giúp em tìm lại ý nghĩa không",
  "lam sao giu long binh yen khi ngay nao cung ra vao benh vien voi con",
  "Bà ngoại đang yếu dần, em muốn những ngày này bên bà thật ý nghĩa thì nên chú tâm điều gì",
  "toi kiet suc vi cham chong om, toi can nho dieu gi de khong guc",
  "Em nên mang theo thông điệp gì trong lòng khi vào phòng bệnh thăm ba mỗi tối",
  "bịnh hoài chán quá, lá bài cho tui xin một lời để sống nhẹ lòng hơn",
  "Đang điều trị dài ngày xa nhà, em tìm niềm vui nhỏ ở đâu",
  "lam sao de thoi tu trach minh khi me om ma minh o xa",
  "Làm sao em đối diện nỗi sợ mỗi lần ngồi chờ ngoài phòng bệnh của con",
  "e dang nam vien 1 minh, buon lam, lomi cho e 1 loi dong vien tu la bai",
  "Chăm mẹ chồng bệnh mà không ai đỡ đần, em cần học bài học gì từ giai đoạn này",
  "song chung voi benh man tinh, toi nen nhin cuoc doi minh theo huong nao",
  "Ba bệnh nặng, em muốn nói lời thương với ba mà ngại, bài gợi ý em mở lòng thế nào",
  "tui đau ốm triền miên nên hay cáu với vợ con, làm răng để lòng dịu lại",
  "minh la dieu duong cham nguoi benh nang moi ngay, lam sao de long khong chai di",
  "Những ngày nằm một chỗ vì bệnh này muốn dạy em điều gì",
  "con om hoai, me don than nhu toi lay gi lam diem tua tinh than",
  "Em vừa nhận tin mình bệnh, chưa nói với ai, em nên ôm lấy cảm xúc này ra sao",
  "cham ong ba gia yeu khien e thay tuoi tre troi qua, e nen nghi sao cho nhe long",
  "Người thương em đang chiến đấu với bệnh tật, em có thể là chỗ dựa cho ảnh bằng cách nào",
  "moi lan vo thuoc xong met ra roi, lam sao giu duoc tinh than cho nhung ngay do",
  "Giữa lúc ốm đau thế này, điều gì trong em vẫn còn đáng để biết ơn",
  "Em đang chăm mẹ bệnh nặng, xin một thông điệp để em vững lòng hơn",
  "Làm sao để giữ được tinh thần trong những ngày hóa trị",
  "toi dang om, xin la bai cho toi mot loi nhan de binh tam",
  "Em nên nhìn những ngày nằm viện này bằng con mắt nào cho nhẹ lòng",
  "cham ba bi tai bien met qua, em can dieu gi de khong guc nga",
  "Ba em đang những ngày cuối, em nên ở bên ba với tâm thế nào",
  "Mạ đau nằm một chỗ, con ở xa không về được, xin một lời nhắn cho lòng con bớt nặng",
  "Em sống chung với bệnh mãn tính đã lâu, lá bài muốn nhắc em điều gì về cách yêu thương bản thân",
  "xin mot thong diep cho nhung nguoi dang cham nguoi than trong vien nhu em",
  "Tôi mới biết mình mang bệnh, tôi cần học cách chấp nhận ra sao",
  "e đang chăm bà ốm, mệt mà ko dám than, e nên giữ lòng mình sao ạ",
  "dieu gi co the lam cho dua tinh than cho em trong thoi gian dieu tri nay",
  "lam the nao de em bot so hai moi lan vao vien cham me",
  "Con tui bệnh hoài, tui kiệt sức quá, xin một lời động viên cho người làm má",
  "y nghia cua quang thoi gian dau om nay voi em la gi",
  "em can mot loi nhan de tiep tuc manh me ben chong dang benh",
  "Trong lúc ngồi ở hành lang bệnh viện trông ba, em nên nghĩ về điều gì để lòng yên",
  "toi gia roi, hay dau yeu, toi nen song nhung ngay nay voi tam the nao",
  "Em vừa trải qua một trận ốm dài, bài học nào em nên mang theo",
  "Răng để lòng mình bình yên khi thấy ôn mệ ngày một yếu hè",
  "nguoi cham benh nhu em nen tu cham soc tinh than minh ra sao",
  "Em muốn một thông điệp để nói lời yêu thương với bà khi bà còn nằm đây",
  "Tui nằm một chỗ dưỡng bệnh buồn quá, lá bài có lời nào an ủi tui hông",
  "lam sao de em khong thay toi loi khi khong o ben ba luc ba om",
  "Giữa những ngày chăm em trai bệnh, em tìm niềm vui nhỏ ở đâu",
];
