// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-businesses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient } from "npm:@supabase/supabase-js@^2.108.1";
import { z } from "npm:zod@^4.4.3";
var BUSINESS_TYPES = ["food", "service", "stay", "travel", "creator", "freelance", "broker", "other"];
var list_businesses_default = defineTool({
  name: "list_businesses",
  title: "Danh s\xE1ch doanh nghi\u1EC7p",
  description: "Tr\u1EA3 v\u1EC1 danh s\xE1ch doanh nghi\u1EC7p \u0111\xE3 \u0111\u01B0\u1EE3c duy\u1EC7t trong c\u1ED9ng \u0111\u1ED3ng Li\xEAn Minh Li\xEAn Doanh. C\xF3 th\u1EC3 l\u1ECDc theo lo\u1EA1i h\xECnh.",
  inputSchema: {
    type: z.enum(BUSINESS_TYPES).optional().describe("Lo\u1EA1i h\xECnh doanh nghi\u1EC7p (t\xF9y ch\u1ECDn)"),
    search: z.string().optional().describe("T\u1EEB kh\xF3a t\xECm trong t\xEAn doanh nghi\u1EC7p (t\xF9y ch\u1ECDn)"),
    limit: z.number().int().min(1).max(50).default(20).describe("S\u1ED1 l\u01B0\u1EE3ng t\u1ED1i \u0111a")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, search, limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("businesses").select("id, name, type, description, address, phone, website, points, is_featured").eq("status", "approved").order("is_featured", { ascending: false }).order("points", { ascending: false }).limit(limit);
    if (type) q = q.eq("type", type);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { businesses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-business.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_business_default = defineTool2({
  name: "get_business",
  title: "Chi ti\u1EBFt doanh nghi\u1EC7p",
  description: "L\u1EA5y th\xF4ng tin chi ti\u1EBFt c\u1EE7a m\u1ED9t doanh nghi\u1EC7p \u0111\xE3 duy\u1EC7t theo ID.",
  inputSchema: {
    id: z2.string().uuid().describe("ID doanh nghi\u1EC7p")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("businesses").select(
      "id, name, type, description, hours_open, hours_close, phone, address, facebook_url, website_url, cover_url, tiktok_url, instagram_url, youtube_url, is_featured, points, level, created_at"
    ).eq("id", id).eq("status", "approved").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Kh\xF4ng t\xECm th\u1EA5y doanh nghi\u1EC7p" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { business: data }
    };
  }
});

// src/lib/mcp/tools/list-offers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_offers_default = defineTool3({
  name: "list_offers",
  title: "Danh s\xE1ch \u01B0u \u0111\xE3i",
  description: "Tr\u1EA3 v\u1EC1 c\xE1c \u01B0u \u0111\xE3i \u0111ang ho\u1EA1t \u0111\u1ED9ng trong c\u1ED9ng \u0111\u1ED3ng Li\xEAn Minh Li\xEAn Doanh.",
  inputSchema: {
    business_id: z3.string().uuid().optional().describe("L\u1ECDc theo ID doanh nghi\u1EC7p (t\xF9y ch\u1ECDn)"),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, limit }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("offers").select("id, business_id, title, description, discount, expires_at, created_at").eq("status", "active").order("created_at", { ascending: false }).limit(limit);
    if (business_id) q = q.eq("business_id", business_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/community-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.1";
var community_stats_default = defineTool4({
  name: "community_stats",
  title: "Th\u1ED1ng k\xEA c\u1ED9ng \u0111\u1ED3ng",
  description: "Tr\u1EA3 v\u1EC1 s\u1ED1 l\u01B0\u1EE3ng th\xE0nh vi\xEAn, doanh nghi\u1EC7p v\xE0 \u01B0u \u0111\xE3i \u0111ang ho\u1EA1t \u0111\u1ED9ng c\u1EE7a Li\xEAn Minh Li\xEAn Doanh.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const [m, b, o] = await Promise.all([
      supabase.from("profiles").select("*", { count: "exact", head: true }).eq("status", "approved"),
      supabase.from("businesses").select("*", { count: "exact", head: true }).eq("status", "approved"),
      supabase.from("offers").select("*", { count: "exact", head: true }).eq("status", "active")
    ]);
    const stats = { members: m.count ?? 0, businesses: b.count ?? 0, offers: o.count ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lien-minh-lien-doanh-mcp",
  title: "Li\xEAn Minh Li\xEAn Doanh",
  version: "0.1.0",
  instructions: "Truy c\u1EADp d\u1EEF li\u1EC7u c\xF4ng khai c\u1EE7a c\u1ED9ng \u0111\u1ED3ng Li\xEAn Minh Li\xEAn Doanh t\u1EA1i \u0110\xE0 L\u1EA1t: danh s\xE1ch doanh nghi\u1EC7p \u0111\xE3 duy\u1EC7t, \u01B0u \u0111\xE3i \u0111ang ho\u1EA1t \u0111\u1ED9ng v\xE0 th\u1ED1ng k\xEA c\u1ED9ng \u0111\u1ED3ng. D\xF9ng list_businesses/get_business \u0111\u1EC3 kh\xE1m ph\xE1 doanh nghi\u1EC7p, list_offers cho \u01B0u \u0111\xE3i, community_stats cho t\u1ED5ng quan.",
  tools: [list_businesses_default, get_business_default, list_offers_default, community_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
